"""
Word lists for Wordle Battle and Drawing Guess games.

Exports:
    WORDLE_SOLUTIONS  - list of ~2300 common 5-letter words (solution pool)
    WORDLE_VALID      - set of ~10000 valid 5-letter guess words (superset of solutions)
    DRAW_WORDS        - list of ~200 easily drawable words by category
"""

# ---------------------------------------------------------------------------
# 1. WORDLE SOLUTIONS  (~2309 common, recognizable 5-letter English words)
# ---------------------------------------------------------------------------
WORDLE_SOLUTIONS = [
    "about", "above", "abuse", "acids", "acres", "acted", "actor", "acute",
    "adapt", "added", "admin", "admit", "adopt", "adult", "after", "again",
    "agent", "aging", "agree", "ahead", "aided", "aimed", "aisle", "alarm",
    "album", "alert", "alien", "align", "alike", "alive", "alley", "allow",
    "alloy", "alone", "along", "aloof", "alpha", "alter", "amber", "amend",
    "amine", "amino", "among", "ample", "amuse", "angel", "anger", "angle",
    "angry", "anime", "ankle", "annex", "antic", "anvil", "apart", "apple",
    "apply", "apron", "arena", "argue", "arise", "armor", "arose", "array",
    "arrow", "arson", "ashes", "aside", "asked", "asset", "atlas", "attic",
    "audio", "audit", "avoid", "await", "awake", "award", "aware", "awful",
    "awoke", "axial", "azure",
    "badge", "badly", "bagel", "baker", "bands", "banks", "baron", "based",
    "bases", "basic", "basin", "basis", "batch", "beach", "beans", "beard",
    "beast", "began", "begin", "begun", "being", "below", "bench", "berry",
    "bible", "bikes", "bills", "birth", "black", "blade", "blame", "bland",
    "blank", "blast", "blaze", "bleak", "bleed", "blend", "bless", "blind",
    "blink", "bliss", "block", "bloke", "blond", "blood", "bloom", "blown",
    "blues", "bluff", "blunt", "blurb", "blurt", "blush", "board", "boast",
    "bolts", "bombs", "bonds", "bones", "bonus", "books", "boost", "boots",
    "booth", "booty", "bored", "borne", "bosom", "bossy", "botch", "bound",
    "brain", "brand", "brass", "brave", "bravo", "brawl", "bread", "break",
    "breed", "brick", "bride", "brief", "brink", "brisk", "broad", "broil",
    "broke", "brook", "broth", "brown", "brush", "brute", "buddy", "budge",
    "build", "built", "bulge", "bulky", "bully", "bunch", "bunny", "burst",
    "buyer",
    "cabin", "cable", "camel", "camps", "canal", "candy", "canoe", "caper",
    "cards", "cargo", "carol", "carry", "carve", "cases", "catch", "cater",
    "cause", "cedar", "chain", "chair", "chalk", "champ", "chant", "chaos",
    "charm", "chart", "chase", "cheap", "cheat", "check", "cheek", "cheer",
    "chess", "chest", "chief", "child", "chili", "chill", "china", "chips",
    "choir", "chord", "chore", "chose", "chunk", "cider", "cigar", "cited",
    "civic", "civil", "claim", "clamp", "clang", "clash", "clasp", "class",
    "clean", "clear", "clerk", "click", "cliff", "climb", "cling", "clock",
    "clone", "close", "cloth", "cloud", "clown", "clubs", "cluck", "clump",
    "clung", "coals", "coast", "coats", "cocoa", "coils", "coins", "color",
    "comet", "comic", "comma", "condo", "coral", "corps", "costs", "couch",
    "could", "count", "coupe", "court", "cover", "covet", "crack", "craft",
    "cramp", "crane", "crash", "crate", "crave", "crawl", "crazy", "creak",
    "cream", "creek", "creep", "crest", "crews", "crime", "crisp", "cross",
    "crowd", "crown", "crude", "cruel", "crush", "cubic", "curry", "curse",
    "curve", "cycle",
    "daily", "dairy", "dance", "dated", "deals", "dealt", "death", "debit",
    "debug", "debut", "decay", "decoy", "decor", "decoy", "delay", "delta",
    "delve", "demon", "demur", "dense", "depot", "depth", "derby", "desks",
    "detox", "devil", "diary", "dicey", "digit", "diner", "dirty", "disco",
    "ditch", "dizzy", "dodge", "doing", "dolls", "donor", "donut", "doors",
    "doses", "doubt", "dough", "downs", "draft", "drain", "drake", "drama",
    "drank", "drape", "drawn", "draws", "dread", "dream", "dress", "dried",
    "drift", "drill", "drink", "drive", "drone", "drops", "drove", "drown",
    "drugs", "drums", "drunk", "dryer", "dryly", "ducal", "ducks", "dummy",
    "dunce", "dunes", "dusty", "dwarf", "dwell", "dying",
    "eager", "eagle", "early", "earth", "eaten", "eater", "edges", "edict",
    "eight", "elbow", "elder", "elect", "elite", "elope", "elude", "email",
    "ember", "emcee", "emoji", "empty", "ended", "enemy", "enjoy", "enact",
    "ensue", "enter", "entry", "envoy", "equal", "equip", "erase", "erode",
    "error", "essay", "ether", "ethic", "evade", "event", "every", "evict",
    "evoke", "exact", "exalt", "exam", "exams", "excel", "exert", "exile",
    "exist", "expat", "extra",
    "fable", "faced", "faces", "facts", "fails", "faint", "fairy", "faith",
    "falls", "false", "fancy", "fatal", "fatty", "fault", "fauna", "favor",
    "feast", "feats", "feeds", "feels", "fence", "ferry", "fetal", "fetch",
    "fever", "fewer", "fiber", "fibre", "field", "fiend", "fifth", "fifty",
    "fight", "files", "films", "filth", "final", "finds", "finer", "fired",
    "fires", "firms", "first", "fixed", "flair", "flake", "flame", "flank",
    "flare", "flash", "flask", "flesh", "flies", "fling", "flint", "float",
    "flock", "flood", "floor", "flora", "floss", "flour", "flows", "fluid",
    "fluke", "flung", "flush", "flute", "focal", "focus", "foggy", "foils",
    "folds", "folks", "folly", "fonts", "foods", "force", "forge", "forgo",
    "forms", "forth", "forty", "forum", "forts", "fosse", "found", "foxes",
    "frame", "frank", "fraud", "freak", "freed", "fresh", "friar", "fried",
    "front", "frost", "froze", "fruit", "fuels", "fully", "funds", "funny",
    "furry", "fused", "fussy", "fuzzy",
    "gains", "games", "gamma", "gases", "gauge", "gavel", "gears", "genes",
    "genre", "ghost", "giant", "gifts", "given", "gives", "gizmo", "gland",
    "glare", "glass", "glaze", "gleam", "glide", "globe", "gloom", "glory",
    "gloss", "glove", "glued", "gnome", "goals", "going", "goods", "goose",
    "gorge", "grace", "grade", "graft", "grain", "grand", "grant", "grape",
    "graph", "grasp", "grass", "grate", "grave", "gravy", "graze", "great",
    "greed", "greek", "green", "greet", "grief", "grill", "grind", "gripe",
    "groan", "groin", "groom", "grope", "gross", "group", "grove", "growl",
    "grown", "grows", "guard", "guess", "guest", "guide", "guild", "guilt",
    "guise", "gulch", "gummy",
    "habit", "hands", "handy", "happy", "hardy", "harsh", "haste", "hasty",
    "hatch", "haunt", "haven", "havoc", "heads", "heart", "heavy", "hedge",
    "heels", "hefty", "heist", "hello", "helps", "hence", "herbs", "herds",
    "hills", "hilly", "hinge", "hints", "hired", "hobby", "holds", "holes",
    "holly", "homes", "honey", "honor", "hooks", "hoped", "hopes", "horde",
    "horns", "horse", "hosts", "hotel", "hound", "hours", "house", "hover",
    "human", "humid", "humor", "hurry", "hyena", "hyper",
    "icing", "ideal", "ideas", "idiom", "idiot", "image", "imply", "inbox",
    "incur", "index", "indie", "inept", "inert", "infer", "inner", "input",
    "inter", "intro", "ionic", "irate", "irony", "issue", "ivory",
    "jaunt", "jeans", "jelly", "jewel", "jiffy", "jimmy", "joint", "joker",
    "jolly", "joust", "judge", "juice", "juicy", "jumbo", "jumps", "juror",
    "dusty",
    "karma", "kayak", "kebab", "kings", "knack", "knead", "kneel", "knelt",
    "knelt", "knife", "knobs", "knock", "knoll", "knots", "known", "knows",
    "koala",
    "label", "labor", "laden", "ladle", "lakes", "lamps", "lands", "lanes",
    "large", "largo", "larva", "laser", "lasts", "latch", "later", "lathe",
    "laugh", "lawns", "layer", "leads", "leapt", "learn", "lease", "least",
    "leave", "ledge", "legal", "lemon", "level", "lever", "light", "liked",
    "liken", "lilac", "limbs", "limit", "linen", "liner", "lines", "lingo",
    "links", "lions", "lipid", "lists", "liter", "liver", "lives", "llama",
    "loads", "loans", "lobby", "local", "locks", "locus", "lodge", "lofty",
    "logic", "login", "looks", "loops", "loose", "lords", "lorry", "loser",
    "loses", "lotus", "lousy", "loved", "lover", "lower", "lowly", "loyal",
    "lucid", "lucky", "lunar", "lunch", "lunge", "lured", "lyric", "lying",
    "magic", "major", "maker", "males", "manor", "maple", "march", "marks",
    "marsh", "masks", "mason", "match", "mated", "mates", "maybe", "mayor",
    "meals", "means", "meant", "medal", "media", "meets", "melee", "melon",
    "mercy", "merge", "merit", "merry", "messy", "metal", "meter", "midst",
    "might", "mills", "mimic", "minds", "mined", "mines", "minor", "minus",
    "mirth", "miser", "misty", "mixed", "mixer", "moans", "model", "modem",
    "modes", "mogul", "moist", "molar", "moldy", "money", "monks", "month",
    "moods", "moose", "moral", "motif", "motor", "motto", "mould", "mound",
    "mount", "mourn", "mouse", "mouth", "moved", "mover", "moves", "movie",
    "muddy", "mural", "murky", "music", "musty", "myths",
    "naive", "named", "names", "nanny", "nasal", "nasty", "naval", "needs",
    "nerve", "never", "newer", "newly", "nexus", "night", "ninth", "noble",
    "nodes", "noise", "noisy", "norms", "north", "notch", "noted", "notes",
    "novel", "nudge", "nurse", "nutty", "nylon",
    "oasis", "occur", "ocean", "oddly", "odour", "offer", "often", "olive",
    "omega", "onset", "opens", "opera", "opted", "optic", "orbit", "order",
    "organ", "other", "ought", "ounce", "outer", "outdo", "outgo", "ovals",
    "ovary", "ovens", "owing", "owner", "oxide", "ozone",
    "paced", "packs", "pages", "pains", "paint", "pairs", "palms", "panel",
    "panic", "paper", "parks", "parts", "party", "pasta", "paste", "patch",
    "paths", "patio", "pause", "peace", "peach", "pearl", "peaks", "pedal",
    "peers", "penal", "pence", "penny", "perch", "peril", "perks", "petty",
    "phase", "phone", "photo", "piano", "picks", "piece", "piled", "pills",
    "pilot", "pinch", "pinto", "pipes", "pitch", "pivot", "pixel", "pizza",
    "place", "plaid", "plain", "plane", "plank", "plans", "plant", "plate",
    "plaza", "plead", "pleat", "plier", "plots", "plows", "pluck", "plumb",
    "plume", "plump", "plums", "plumb", "plunk", "plush", "poems", "poets",
    "point", "poise", "poker", "polar", "polls", "ponds", "pools", "porch",
    "pores", "ports", "posed", "poser", "posit", "posts", "pouch", "pound",
    "power", "prank", "prawn", "press", "price", "pride", "prime", "print",
    "prior", "prism", "privy", "prize", "probe", "prone", "proof", "prose",
    "proud", "prove", "prowl", "proxy", "prude", "prune", "psalm", "pulse",
    "pumps", "punch", "pupil", "puppy", "purge", "purse", "pygmy",
    "quack", "quake", "qualm", "queen", "query", "quest", "queue", "quick",
    "quiet", "quilt", "quirk", "quite", "quota", "quote",
    "radar", "radio", "raids", "rails", "rainy", "raise", "rally", "ranch",
    "range", "ranks", "rapid", "rated", "rates", "ratio", "rayon", "reach",
    "react", "reads", "ready", "realm", "reaps", "rebel", "recap", "recon",
    "reeds", "refer", "reign", "reins", "relax", "relay", "relic", "remit",
    "renal", "renew", "repay", "repel", "reply", "resin", "rests", "retro",
    "rider", "ridge", "rifle", "right", "rigid", "rings", "rinse", "riots",
    "risen", "risks", "risky", "risen", "rites", "rival", "river", "roads",
    "roast", "robin", "robot", "rocks", "rocky", "rogue", "roles", "roman",
    "rooms", "roots", "ropes", "roses", "rotor", "rouge", "rough", "round",
    "route", "royal", "rugby", "ruins", "ruled", "ruler", "rules", "rumor",
    "rural", "rusty",
    "sadly", "saint", "salad", "sales", "salon", "salsa", "salty", "salve",
    "sands", "sandy", "satin", "sauce", "sauna", "saved", "savor", "scale",
    "scalp", "scams", "scant", "scare", "scarf", "scary", "scene", "scent",
    "scope", "score", "scorn", "scout", "scram", "scrap", "screw", "scrub",
    "seats", "seeds", "seize", "sense", "serum", "serve", "setup", "seven",
    "sever", "sewer", "shade", "shaft", "shake", "shall", "shame", "shape",
    "share", "shark", "sharp", "shave", "shawl", "shear", "sheds", "sheen",
    "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine", "shiny",
    "ships", "shire", "shirt", "shock", "shoes", "shook", "shoot", "shops",
    "shore", "short", "shots", "shout", "shove", "shown", "shows", "shrub",
    "shrug", "sided", "sides", "siege", "sight", "sigma", "signs", "silly",
    "since", "siren", "sites", "sixth", "sixty", "sizes", "skate", "skimp",
    "skill", "skull", "skunk", "slabs", "slack", "slain", "slang", "slant",
    "slash", "slate", "slave", "sleek", "sleep", "sleet", "slept", "slice",
    "slide", "slime", "slimy", "slope", "sloth", "slugs", "slump", "smack",
    "small", "smart", "smash", "smear", "smell", "smile", "smirk", "smite",
    "smith", "smoke", "smoky", "snack", "snail", "snake", "snare", "sneak",
    "sniff", "snore", "snout", "snowy", "sober", "solar", "solid", "solve",
    "songs", "sonic", "sorry", "sorts", "souls", "sound", "south", "space",
    "spare", "spark", "spawn", "speak", "spear", "specs", "speed", "spell",
    "spend", "spent", "spice", "spicy", "spied", "spill", "spine", "spoke",
    "spoon", "sport", "spots", "spray", "spree", "sprig", "squad", "squat",
    "squid", "stack", "staff", "stage", "stain", "stair", "stake", "stale",
    "stalk", "stall", "stamp", "stand", "stank", "stare", "stark", "start",
    "state", "stays", "steak", "steal", "steam", "steel", "steep", "steer",
    "stems", "steps", "stern", "stew", "stick", "stiff", "still", "sting",
    "stink", "stint", "stock", "stoic", "stoke", "stole", "stomp", "stone",
    "stood", "stool", "stoop", "stops", "store", "stork", "storm", "story",
    "stout", "stove", "strap", "straw", "stray", "strip", "stuck", "study",
    "stuff", "stump", "stung", "stunk", "stunt", "style", "suave", "sugar",
    "suite", "suits", "sunny", "super", "surge", "sushi", "swamp", "swarm",
    "swear", "sweat", "sweep", "sweet", "swept", "swift", "swing", "swipe",
    "swirl", "swore", "sworn", "swung", "syrup",
    "table", "tacit", "taint", "taken", "tales", "talks", "tally", "tangy",
    "tanks", "tapes", "tasks", "taste", "tasty", "taxes", "teach", "teams",
    "tears", "tease", "teddy", "teens", "teeth", "tempo", "tends", "tenor",
    "tense", "tenth", "terms", "tests", "texts", "thank", "theft", "theme",
    "thick", "thief", "thigh", "thing", "think", "third", "thorn", "those",
    "three", "threw", "throw", "thumb", "tidal", "tiger", "tight", "tiles",
    "timer", "times", "timid", "tipsy", "tired", "titan", "title", "toast",
    "today", "token", "tolls", "tombs", "toned", "tones", "tonic", "tools",
    "topic", "torch", "total", "touch", "tough", "tours", "towel", "tower",
    "towns", "toxic", "trace", "track", "tract", "trade", "trail", "train",
    "trait", "tramp", "trans", "traps", "trash", "treat", "trend", "trial",
    "tribe", "trick", "tried", "tries", "trims", "trite", "troll", "troop",
    "trout", "truck", "truly", "trump", "trunk", "trust", "truth", "tulip",
    "tumor", "tuned", "tuner", "tunes", "turbo", "turns", "tutor", "tweed",
    "tweet", "twice", "twigs", "twirl", "twist", "typos",
    "ultra", "uncle", "uncut", "under", "undid", "undue", "unfit", "unhip",
    "union", "unite", "unity", "unlit", "until", "unwed", "upper", "upset",
    "urban", "usage", "users", "usher", "using", "usual", "utter",
    "vague", "valid", "value", "valve", "vapor", "vault", "vegan", "veins",
    "veils", "venue", "verse", "vexed", "video", "vigor", "vigil", "vinyl",
    "viola", "viral", "virus", "visit", "visor", "vista", "vital", "vivid",
    "vocal", "vodka", "vogue", "voice", "voted", "voter", "vouch", "vowel",
    "vowed",
    "wacky", "waged", "wages", "wagon", "waist", "walks", "walls", "wanna",
    "wards", "warns", "waste", "watch", "water", "waved", "waves", "weary",
    "weave", "wedge", "weeds", "weigh", "weird", "wells", "whale", "wheat",
    "wheel", "where", "which", "while", "whine", "whirl", "white", "whole",
    "whose", "wider", "widow", "width", "wield", "wines", "wings", "wires",
    "witch", "witty", "woken", "woman", "women", "woods", "wordy", "works",
    "world", "worms", "worry", "worse", "worst", "worth", "would", "wound",
    "wrath", "wreck", "wrist", "write", "wrong", "wrote",
    "yacht", "yards", "years", "yeast", "yield", "young", "yours", "youth",
    "zones", "abbey", "abort", "abode", "abyss", "acorn", "added", "adept",
    "adobe", "aegis", "afoot", "agile", "agony", "aisle", "algae", "alibi",
    "alkyl", "allay", "aloft", "amass", "amber", "amble", "ample", "angst",
    "annoy", "annul", "aorta", "aphid", "aptly", "arbor", "ardor", "array",
    "ascot", "aster", "atone", "avail", "avert", "avian", "axiom",
    "bacon", "badge", "badly", "baits", "balmy", "baron", "baste", "beach",
    "beard", "bench", "beset", "biddy", "bigot", "binge", "biome", "birch",
    "bison", "blade", "blare", "bleat", "blimp", "bloat", "blown", "blues",
    "blunt", "blurb", "board", "bogus", "bolts", "booze", "bossy", "bower",
    "brace", "braid", "brain", "brake", "brand", "brash", "brass", "brawl",
    "brawn", "bread", "bribe", "briny", "brisk", "brown", "brunt", "budge",
    "buggy", "bugle", "build", "bulge", "bumpy", "bunny", "buyer",
    "cache", "cadet", "cairn", "cedar", "charm", "chewy", "chick", "chime",
    "choke", "chunk", "churn", "cider", "cigar", "cinch", "circa", "civil",
    "clank", "cleat", "clerk", "click", "cliff", "climb", "clink", "cloak",
    "cloth", "clout", "clown", "coach", "coapt", "cocoa", "comic", "coral",
    "couch", "could", "count", "coupe", "cover", "covet", "crack", "crane",
    "crass", "crate", "crave", "crawl", "creed", "creep", "crisp", "croak",
    "crock", "crook", "cross", "croup", "crude", "cruel", "crust", "cubic",
    "cumin", "cushy", "cutie",
    "daisy", "dance", "dandy", "darts", "dated", "dazed", "debut", "decal",
    "decor", "decoy", "deity", "delay", "delve", "denim", "depot", "depth",
    "derby", "detox", "deuce", "diary", "diner", "disco", "ditto", "dizzy",
    "dodge", "dogma", "dolly", "donor", "donut", "dorky", "doubt", "dough",
    "dowdy", "dowry", "dozed", "draft", "drain", "drape", "dread", "drill",
    "drink", "droit", "droll", "drool", "droop", "druid", "dryly", "ducal",
    "dunce", "dusky", "dusty", "dwarf", "dwell",
    "easel", "eater", "edict", "eerie", "eight", "elate", "elbow", "elder",
    "elect", "elfin", "elite", "elope", "elude", "email", "emcee", "ensue",
    "envoy", "epoch", "equip", "erupt", "essay", "ether", "ethic", "evade",
    "event", "every", "evict", "evoke", "exalt", "exact", "exams", "exile",
    "expat", "extra",
    "fable", "faced", "facet", "facts", "faint", "fairy", "faith", "false",
    "farce", "fatal", "fatty", "fauna", "feast", "feign", "fella", "felon",
    "ferry", "fetal", "fetch", "fever", "fibre", "field", "fiend", "fifth",
    "fifty", "filth", "final", "finch", "first", "fishy", "fixed", "fizzy",
    "fjord", "flail", "flair", "flake", "flaky", "flame", "flank", "flare",
    "flask", "flaxy", "fleck", "flesh", "flick", "flier", "fling", "flint",
    "float", "flock", "flood", "flora", "floss", "flour", "flown", "fluff",
    "fluid", "fluke", "flung", "flush", "flute", "focal", "focus", "foggy",
    "foils", "folly", "force", "forge", "forgo", "forte", "forth", "forty",
    "forum", "found", "frame", "frank", "fraud", "freak", "freed", "fresh",
    "friar", "front", "frost", "froze", "fruit", "fully", "funds", "fungi",
    "funky", "funny", "furry", "fussy", "fuzzy",
    "gaily", "gamer", "gamma", "gaudy", "gauge", "gaunt", "gavel", "genre",
    "ghost", "giant", "giddy", "given", "gizmo", "gland", "glare", "glass",
    "glaze", "gleam", "glean", "glide", "glint", "globe", "gloom", "glory",
    "gloss", "gnome", "godly", "golem", "goose", "gorge", "gouge", "grace",
    "grade", "graft", "grain", "grand", "grant", "graph", "grasp", "grass",
    "grate", "grave", "gravy", "graze", "great", "greed", "green", "greet",
    "grief", "grill", "grime", "grimy", "grind", "gripe", "groan", "groin",
    "groom", "grope", "gross", "group", "grove", "growl", "grown", "gruff",
    "guard", "guess", "guide", "guild", "guilt", "guise", "gulch", "gummy",
    "guppy", "gusto", "gusty",
    "hands", "handy", "happy", "hardy", "haste", "hasty", "hatch", "haunt",
    "haven", "havoc", "heady", "heaps", "heart", "heavy", "hedge", "hefty",
    "heist", "hello", "hence", "herbs", "hilly", "hinge", "hippo", "hitch",
    "hoard", "hobby", "holly", "homer", "honey", "honor", "hoped", "horde",
    "horny", "horse", "hotel", "hotly", "hound", "house", "hover", "howdy",
    "human", "humid", "humps", "humor", "husky", "hyena", "hyper",
    "icing", "ideal", "idiom", "idiot", "igloo", "image", "imply", "incur",
    "index", "indie", "inept", "inert", "infer", "inner", "input", "intro",
    "ionic", "irate", "irony", "issue", "ivory",
    "jaunt", "jazzy", "jelly", "jewel", "jiffy", "joint", "joker", "jolly",
    "joust", "judge", "juice", "juicy", "jumbo", "jumpy", "juror",
    "karma", "kayak", "kebab", "kinky", "kiosk", "knack", "knead", "kneel",
    "knelt", "knife", "knock", "knoll", "known", "koala",
    "label", "labor", "laced", "laden", "ladle", "lance", "lapse", "large",
    "larva", "laser", "latch", "later", "lathe", "laugh", "layer", "learn",
    "lease", "least", "leave", "ledge", "legal", "lemon", "level", "lever",
    "light", "lilac", "limbo", "limit", "linen", "liner", "lingo", "lipid",
    "liter", "liver", "llama", "lobby", "local", "locus", "lodge", "lofty",
    "logic", "login", "loose", "lorry", "loser", "lotus", "lousy", "lover",
    "lower", "lowly", "loyal", "lucid", "lucky", "lumen", "lunar", "lunch",
    "lunge", "lyric",
    "macho", "macro", "magic", "major", "maker", "mango", "manor", "maple",
    "marsh", "match", "maybe", "mayor", "mealy", "medal", "media", "melee",
    "melon", "mercy", "merge", "merit", "merry", "messy", "metal", "meter",
    "metro", "midst", "might", "mimic", "mince", "minor", "minus", "mirth",
    "miser", "misty", "miter", "model", "modem", "mogul", "moist", "molar",
    "moldy", "money", "month", "moody", "moose", "moral", "morph", "mossy",
    "motel", "motif", "motor", "motto", "mound", "mount", "mourn", "mouse",
    "mouth", "movie", "muddy", "mulch", "mural", "murky", "mushy", "music",
    "musky", "musty", "myths",
    "naive", "named", "nanny", "nasal", "nasty", "naval", "nerve", "never",
    "nexus", "nifty", "night", "ninth", "noble", "noise", "noisy", "nomad",
    "north", "notch", "noted", "novel", "nudge", "nurse", "nutty", "nylon",
    "nymph",
    "oasis", "occur", "ocean", "oddly", "offer", "often", "olive", "omega",
    "onset", "opera", "optic", "orbit", "order", "organ", "other", "ought",
    "ounce", "outer", "outdo", "ovary", "owing", "owner", "oxide", "ozone",
    "paced", "paint", "panel", "panic", "paper", "parka", "parse", "party",
    "pasta", "paste", "patch", "patio", "pause", "peace", "peach", "pearl",
    "pedal", "penal", "penny", "perch", "peril", "perky", "pesky", "petal",
    "petty", "phase", "phone", "photo", "piano", "picky", "piece", "pilot",
    "pinch", "piper", "pitch", "pivot", "pixel", "pizza", "place", "plaid",
    "plain", "plane", "plank", "plant", "plate", "plaza", "plead", "pleat",
    "pluck", "plumb", "plume", "plump", "plunk", "plush", "poach", "plumb",
    "point", "poise", "poker", "polar", "polka", "polyp", "poppy", "porch",
    "poser", "posit", "pouch", "pound", "power", "prank", "prawn", "press",
    "price", "pride", "prime", "print", "prior", "prism", "privy", "prize",
    "probe", "prone", "proof", "prose", "proud", "prove", "prowl", "proxy",
    "prude", "prune", "psalm", "pulse", "punch", "pupil", "puppy", "purge",
    "purse",
    "quack", "qualm", "queen", "query", "quest", "queue", "quick", "quiet",
    "quilt", "quirk", "quota", "quote",
    "radar", "radio", "rainy", "raise", "rally", "ranch", "range", "rapid",
    "ratio", "rayon", "reach", "react", "ready", "realm", "rebel", "recap",
    "recon", "refer", "reign", "relax", "relay", "relic", "remit", "renal",
    "renew", "repay", "repel", "reply", "resin", "retro", "rider", "ridge",
    "rifle", "right", "rigid", "rinse", "risky", "rival", "river", "roast",
    "robin", "robot", "rocky", "rogue", "roman", "roost", "rotor", "rouge",
    "rough", "round", "route", "rowdy", "royal", "rugby", "ruler", "rumba",
    "rumor", "rural", "rusty",
    "sadly", "saint", "salad", "salon", "salsa", "salty", "salve", "sandy",
    "satin", "sauce", "sauna", "savor", "scale", "scalp", "scant", "scare",
    "scarf", "scary", "scene", "scent", "scope", "score", "scorn", "scout",
    "scram", "scrap", "screw", "scrub", "seize", "sense", "serum", "serve",
    "setup", "seven", "sever", "sewer", "shade", "shaft", "shake", "shame",
    "shape", "share", "shark", "sharp", "shave", "shawl", "shear", "sheen",
    "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shine", "shiny",
    "shire", "shirt", "shock", "shoot", "shore", "short", "shout", "shove",
    "shown", "shrub", "shrug", "sight", "silly", "since", "siren", "sixth",
    "sixty", "skate", "skill", "skull", "skunk", "slack", "slain", "slang",
    "slant", "slash", "slate", "slave", "sleek", "sleep", "sleet", "slept",
    "slice", "slide", "slime", "slope", "sloth", "slump", "smack", "small",
    "smart", "smash", "smear", "smell", "smile", "smirk", "smith", "smoke",
    "smoky", "snack", "snail", "snake", "snare", "sneak", "sniff", "snore",
    "snout", "snowy", "sober", "solar", "solid", "solve", "sonic", "sorry",
    "sound", "south", "space", "spare", "spark", "spawn", "speak", "spear",
    "speed", "spell", "spend", "spent", "spice", "spicy", "spill", "spine",
    "spoke", "spoon", "sport", "spray", "spree", "squad", "squat", "squid",
    "stack", "staff", "stage", "stain", "stair", "stake", "stale", "stalk",
    "stall", "stamp", "stand", "stare", "stark", "start", "stash", "state",
    "steak", "steal", "steam", "steel", "steep", "steer", "stern", "stick",
    "stiff", "still", "sting", "stink", "stint", "stock", "stoic", "stoke",
    "stole", "stomp", "stone", "stood", "stool", "stoop", "store", "stork",
    "storm", "story", "stout", "stove", "strap", "straw", "stray", "strip",
    "stuck", "study", "stuff", "stump", "stung", "stunk", "stunt", "style",
    "suave", "sugar", "suite", "sunny", "super", "surge", "sushi", "swamp",
    "swarm", "swear", "sweat", "sweep", "sweet", "swept", "swift", "swing",
    "swipe", "swirl", "swore", "sworn", "swung", "syrup",
    "table", "tacit", "taint", "taken", "tales", "tally", "tangy", "taste",
    "tasty", "taunt", "teach", "tease", "teddy", "teeth", "tempo", "tense",
    "tenth", "thank", "theft", "theme", "thick", "thief", "thigh", "thing",
    "think", "third", "thorn", "those", "three", "threw", "throw", "thumb",
    "tidal", "tiger", "tight", "timer", "timid", "tipsy", "tired", "titan",
    "title", "toast", "today", "token", "tonic", "topic", "torch", "total",
    "touch", "tough", "towel", "tower", "toxic", "trace", "track", "tract",
    "trade", "trail", "train", "trait", "trash", "treat", "trend", "trial",
    "tribe", "trick", "tried", "trite", "troll", "troop", "trout", "truck",
    "truly", "trump", "trunk", "trust", "truth", "tulip", "tumor", "tuner",
    "turbo", "tutor", "tweed", "tweet", "twice", "twigs", "twirl", "twist",
    "ultra", "uncle", "under", "undid", "undue", "unfit", "union", "unite",
    "unity", "until", "upper", "upset", "urban", "usage", "usual", "utter",
    "vague", "valid", "value", "valve", "vapor", "vault", "vegan", "venue",
    "verse", "video", "vigor", "vigil", "vinyl", "viola", "viral", "virus",
    "visit", "visor", "vista", "vital", "vivid", "vocal", "vodka", "vogue",
    "voice", "voter", "vouch", "vowel",
    "wacky", "waged", "wagon", "waist", "waste", "watch", "water", "weary",
    "weave", "wedge", "weigh", "weird", "whale", "wheat", "wheel", "where",
    "which", "while", "whine", "whirl", "white", "whole", "whose", "wider",
    "widow", "width", "wield", "witch", "witty", "woken", "woman", "women",
    "world", "worry", "worse", "worst", "worth", "would", "wound", "wrath",
    "wreck", "wrist", "write", "wrong", "wrote",
    "yacht", "yards", "yearn", "yeast", "yield", "young", "youth",
    "zesty", "zones",
]

# Deduplicate while preserving order, and filter to exactly 5 letters
_seen = set()
_clean = []
for _w in WORDLE_SOLUTIONS:
    _w = _w.strip().lower()
    if len(_w) == 5 and _w not in _seen:
        _seen.add(_w)
        _clean.append(_w)
WORDLE_SOLUTIONS = _clean

# ---------------------------------------------------------------------------
# 2. WORDLE VALID GUESSES  (~10000 accepted 5-letter words, superset of solutions)
# ---------------------------------------------------------------------------
WORDLE_VALID = set(WORDLE_SOLUTIONS) | {
    # A
    "aahed", "aalii", "aargh", "abaca", "abaci", "aback", "abaft", "abamp",
    "abase", "abash", "abate", "abaya", "abbey", "abbot", "abeam", "abele",
    "abets", "abhor", "abide", "abled", "abler", "ables", "abmho", "abode",
    "abohm", "abort", "about", "above", "absit", "abuse", "abuts", "abuzz",
    "abyes", "abyss", "acerb", "acers", "aceta", "ached", "aches", "acids",
    "acidy", "acing", "acini", "ackee", "acmes", "acned", "acnes", "acock",
    "acold", "acorn", "acred", "acres", "acrid", "acted", "actin", "actor",
    "acute", "adage", "adapt", "addax", "added", "adder", "addle", "adeem",
    "adept", "adieu", "adios", "admit", "admix", "adobe", "adopt", "adore",
    "adorn", "adult", "adust", "advil", "aegis", "aeons", "aerie", "affix",
    "afoot", "afore", "after", "again", "agama", "agape", "agate", "agave",
    "agent", "agers", "aggro", "agile", "aging", "agios", "agism", "agist",
    "aglet", "aglow", "agone", "agons", "agony", "agora", "agree", "ahead",
    "ahold", "aided", "aider", "aides", "ailed", "aimed", "aimer", "aioli",
    "aired", "airer", "airns", "airth", "airts", "aisle", "alack", "alamo",
    "alarm", "album", "alder", "alert", "algae", "algal", "alias", "alibi",
    "alien", "align", "alike", "aline", "alive", "allay", "alley", "allot",
    "allow", "alloy", "aloes", "aloft", "aloha", "alone", "along", "aloof",
    "aloud", "alpha", "altar", "alter", "altos", "alums", "amass", "amaze",
    "amber", "ambit", "amble", "ameba", "amend", "amine", "amino", "amiss",
    "amity", "among", "amour", "ample", "amply", "amuck", "amuse", "angel",
    "anger", "angle", "angry", "angst", "anime", "anion", "anise", "ankle",
    "annex", "annoy", "annul", "annum", "anode", "antic", "anvil", "aorta",
    "apart", "aphid", "aphis", "apian", "aping", "apnea", "apple", "apply",
    "apron", "aptly", "aquas", "arbor", "ardor", "arena", "argue", "argus",
    "arise", "armor", "aroma", "arose", "array", "arrow", "arses", "arson",
    "asana", "ascot", "ashed", "ashen", "ashes", "aside", "asked", "asker",
    "askew", "aspen", "aspic", "asset", "atilt", "atlas", "atoll", "atoms",
    "atone", "attic", "audio", "audit", "auger", "augur", "aunts", "aunty",
    "avail", "avert", "avian", "avoid", "await", "awake", "award", "aware",
    "awful", "awing", "awoke", "axial", "axils", "axing", "axiom", "axion",
    "axles", "azote", "azure",
    # B
    "babel", "babes", "backs", "bacon", "badge", "badly", "bagel", "baggy",
    "bails", "baits", "baked", "baker", "bakes", "baldy", "baled", "baler",
    "bales", "balks", "balky", "balls", "balms", "balmy", "balsa", "banal",
    "bands", "banes", "bangs", "banjo", "banks", "barbs", "bards", "bared",
    "barer", "bares", "barfs", "barge", "barks", "barmy", "barns", "baron",
    "barre", "barrs", "basal", "based", "baser", "bases", "basic", "basil",
    "basin", "basis", "basks", "batch", "bated", "bates", "bathe", "baths",
    "batik", "baton", "batts", "batty", "bawds", "bawdy", "bawls", "bayou",
    "beach", "beads", "beady", "beaks", "beams", "beamy", "beans", "beard",
    "bears", "beast", "beats", "beaus", "beaux", "bebop", "becks", "bedew",
    "bedim", "began", "begat", "beget", "begin", "begot", "begun", "being",
    "belay", "belch", "belie", "belle", "bells", "belly", "below", "belts",
    "bench", "bends", "bendy", "berry", "berth", "beset", "betel", "bevel",
    "bible", "bicep", "biddy", "bigot", "bikes", "bilge", "bills", "billy",
    "bimbo", "binds", "binge", "bingo", "biome", "biped", "birch", "birds",
    "birth", "bison", "black", "blade", "blame", "bland", "blank", "blare",
    "blase", "blast", "blaze", "bleak", "bleat", "bleed", "blend", "bless",
    "blimp", "blind", "blink", "bliss", "blitz", "bloat", "blobs", "block",
    "bloke", "blond", "blood", "bloom", "blown", "blows", "bluer", "blues",
    "bluff", "blunt", "blurb", "blurs", "blurt", "blush", "board", "boars",
    "boast", "boats", "bobby", "bogey", "boggy", "bogus", "boils", "bolts",
    "bolus", "bombs", "bonds", "boned", "boner", "bones", "bongo", "bonus",
    "booby", "books", "booms", "boomy", "boons", "boost", "booth", "boots",
    "booty", "booze", "boozy", "bored", "borer", "borne", "boron", "bosom",
    "bossy", "botch", "bound", "bowed", "bowel", "bower", "bowls", "boxed",
    "boxer", "boxes", "brace", "bract", "braid", "brain", "brake", "brand",
    "brash", "brass", "brave", "bravo", "brawl", "brawn", "brays", "bread",
    "break", "breed", "brick", "bride", "brief", "brine", "bring", "brink",
    "briny", "brisk", "broad", "broil", "broke", "brook", "brood", "brook",
    "broth", "brown", "brows", "bruin", "brush", "brute", "bucks", "buddy",
    "budge", "buggy", "bugle", "build", "built", "bulbs", "bulge", "bulky",
    "bully", "bumps", "bumpy", "bunch", "bunks", "bunny", "buoys", "burly",
    "burns", "burnt", "burps", "burro", "burst", "buses", "bushy", "busts",
    "busty", "butch", "butte", "butts", "buyer", "bylaw", "bytes",
    # C
    "cabal", "cabby", "cabin", "cable", "cache", "cacti", "cadet", "caddy",
    "cairn", "caked", "cakes", "calls", "calms", "camel", "cameo", "camps",
    "canal", "candy", "canes", "canoe", "canon", "caper", "capon", "cards",
    "cared", "carer", "cares", "cargo", "carol", "carry", "carte", "carve",
    "cased", "cases", "catch", "cater", "cause", "caves", "cedar", "cells",
    "chain", "chair", "chalk", "champ", "chant", "chaos", "chaps", "charm",
    "chart", "chase", "cheap", "cheat", "check", "cheek", "cheer", "chess",
    "chest", "chewy", "chick", "chide", "chief", "child", "chili", "chill",
    "chime", "china", "chips", "choir", "choke", "chord", "chore", "chose",
    "chunk", "churn", "chute", "cider", "cigar", "cinch", "circa", "cited",
    "cites", "civet", "civic", "civil", "clack", "clads", "claim", "clamp",
    "clams", "clang", "clank", "clans", "claps", "clash", "clasp", "class",
    "claws", "clays", "clean", "clear", "cleat", "clerk", "click", "cliff",
    "climb", "cling", "clink", "clips", "cloak", "clock", "clone", "close",
    "cloth", "cloud", "clout", "clove", "clown", "clubs", "cluck", "clued",
    "clues", "clump", "clung", "clunk", "coals", "coast", "coats", "cobra",
    "cocoa", "codes", "coils", "coins", "colon", "color", "colts", "combo",
    "comet", "comic", "comma", "condo", "coned", "cones", "coops", "coral",
    "cords", "cored", "cores", "corgi", "corks", "corns", "corny", "corps",
    "coset", "costs", "couch", "could", "count", "coupe", "coups", "court",
    "cover", "covet", "crack", "craft", "crags", "cramp", "crane", "crank",
    "crape", "crash", "crass", "crate", "crave", "crawl", "craze", "crazy",
    "creak", "cream", "creed", "creek", "creep", "creme", "crept", "cress",
    "crest", "crews", "crick", "cried", "cries", "crime", "crimp", "crisp",
    "croak", "crock", "crony", "crook", "crops", "cross", "croup", "crowd",
    "crown", "crude", "cruel", "cruet", "crumb", "crush", "crust", "crypt",
    "cubed", "cubes", "cubic", "cumin", "cupid", "curds", "cured", "cures",
    "curls", "curly", "curry", "curse", "curve", "curvy", "cushy", "cutie",
    "cycle",
    # D
    "daddy", "daily", "dairy", "daisy", "dance", "dandy", "dared", "darer",
    "dares", "darks", "darns", "darts", "dated", "dater", "dates", "datum",
    "daunt", "dawns", "dazed", "deals", "dealt", "deans", "death", "debit",
    "debug", "debut", "decal", "decay", "decks", "decor", "decoy", "decoy",
    "decry", "deeds", "deity", "delay", "delta", "delve", "demon", "demur",
    "denim", "dense", "depot", "depth", "derby", "desks", "deter", "detox",
    "deuce", "devil", "diary", "diced", "dicer", "dices", "dicey", "digit",
    "dimly", "dinar", "dined", "diner", "dines", "dingo", "dingy", "dirty",
    "disco", "disks", "ditch", "ditto", "ditty", "divan", "diver", "dives",
    "dizzy", "docks", "dodge", "dodgy", "dogma", "doing", "dolls", "dolly",
    "donor", "donut", "doors", "dorky", "doses", "dotty", "doubt", "dough",
    "douse", "dowdy", "downs", "dowry", "dozed", "dozen", "draft", "drain",
    "drake", "drama", "drank", "drape", "drawn", "draws", "dread", "dream",
    "dress", "dried", "drier", "drift", "drill", "drink", "drips", "drive",
    "droit", "droll", "drone", "drool", "droop", "drops", "dross", "drove",
    "drown", "drugs", "drums", "drunk", "dryer", "dryly", "ducal", "ducks",
    "ducky", "ducts", "duffs", "dulls", "dully", "dummy", "dumps", "dumpy",
    "dunce", "dunes", "dunks", "dunno", "duped", "dupes", "dusty", "dutch",
    "dwarf", "dwell", "dwelt", "dying",
    # E
    "eager", "eagle", "early", "earns", "earth", "eased", "easel", "eaten",
    "eater", "eaves", "ebbed", "ebony", "edged", "edger", "edges", "edged",
    "edict", "edify", "eerie", "eight", "elate", "elbow", "elder", "elect",
    "elfin", "elite", "elope", "elude", "elves", "email", "embed", "ember",
    "emcee", "emoji", "emote", "empty", "enact", "ended", "endow", "enemy",
    "enjoy", "ennui", "ensue", "enter", "entry", "envoy", "epoch", "equal",
    "equip", "erase", "erode", "error", "erupt", "essay", "ether", "ethic",
    "evade", "event", "every", "evict", "evoke", "exact", "exalt", "exams",
    "exams", "excel", "exert", "exile", "exist", "expat", "expel", "extra",
    "exude", "exult", "eying", "eyrie",
    # F
    "fable", "faced", "facer", "faces", "facet", "facts", "faddy", "faded",
    "fails", "faint", "fairy", "faith", "faked", "faker", "fakes", "falls",
    "false", "famed", "fancy", "fangs", "farce", "fared", "fares", "farms",
    "fatal", "fatty", "fault", "fauna", "favor", "feast", "feats", "feeds",
    "feels", "feign", "feint", "fella", "felon", "felts", "femur", "fence",
    "fends", "feral", "ferry", "fetal", "fetch", "fetid", "fetus", "feud",
    "feuds", "fever", "fewer", "fiber", "fibre", "field", "fiend", "fiery",
    "fifth", "fifty", "fight", "filch", "filed", "files", "filet", "fills",
    "filly", "films", "filmy", "filth", "final", "finch", "finds", "fined",
    "finer", "fines", "fired", "fires", "firms", "first", "fishy", "fixed",
    "fixer", "fixes", "fizzy", "fjord", "flack", "flags", "flail", "flair",
    "flake", "flaky", "flame", "flank", "flaps", "flare", "flash", "flask",
    "flats", "flaws", "flaxy", "fleas", "fleck", "flesh", "flick", "flier",
    "flies", "fling", "flint", "flips", "flirt", "float", "flock", "flogs",
    "flood", "floor", "flora", "floss", "flour", "flout", "flows", "flubs",
    "flubs", "fluff", "fluid", "fluke", "fluky", "flung", "flunk", "flush",
    "flute", "focal", "focus", "foggy", "foils", "folds", "folio", "folks",
    "folly", "fonts", "foods", "foray", "force", "forge", "forgo", "forks",
    "forms", "forte", "forth", "forty", "forum", "forts", "found", "fount",
    "fours", "foxes", "foyer", "frail", "frame", "frank", "fraud", "frays",
    "freak", "freed", "fresh", "friar", "fried", "fries", "frill", "frisk",
    "front", "frost", "froth", "frown", "froze", "fruit", "frump", "fuels",
    "fully", "fumes", "funds", "fungi", "funky", "funny", "furry", "fused",
    "fuses", "fussy", "fuzzy",
    # G
    "gaily", "gains", "galas", "gales", "gamer", "games", "gamma", "gamut",
    "gangs", "gaped", "gapes", "garbs", "gases", "gasps", "gates", "gaudy",
    "gauge", "gaunt", "gauze", "gauzy", "gavel", "gazer", "gazes", "gears",
    "gecko", "geeks", "geeky", "genes", "genie", "genre", "genus", "germs",
    "ghost", "giant", "giddy", "gifts", "gilds", "gills", "given", "giver",
    "gives", "gizmo", "glade", "gland", "glare", "glass", "glaze", "gleam",
    "glean", "glide", "glint", "gloat", "globe", "gloom", "glory", "gloss",
    "glove", "glows", "glued", "glues", "gluey", "glyph", "gnome", "goads",
    "goals", "goats", "godly", "going", "golds", "golem", "golfs", "goner",
    "gongs", "goods", "gooey", "goofs", "goofy", "goose", "gorge", "gory",
    "gouge", "gourd", "grace", "grade", "graft", "grail", "grain", "grams",
    "grand", "grant", "grape", "graph", "grasp", "grass", "grate", "grave",
    "gravy", "grays", "graze", "great", "greed", "green", "greet", "grief",
    "grill", "grime", "grimy", "grind", "grins", "gripe", "grips", "groan",
    "groin", "groom", "grope", "gross", "group", "grout", "grove", "growl",
    "grown", "grows", "grubs", "gruel", "gruff", "grump", "grunt", "guano",
    "guard", "guava", "guess", "guest", "guide", "guild", "guilt", "guise",
    "gulch", "gulls", "gulps", "gummy", "gumpy", "gunky", "guppy", "gusto",
    "gusty", "guyed",
    # H
    "habit", "hacky", "hairs", "hairy", "halal", "haler", "hales", "halls",
    "halts", "halve", "hands", "handy", "hangs", "happy", "hardy", "harem",
    "hares", "harks", "harms", "harps", "harpy", "harsh", "haste", "hasty",
    "hatch", "hated", "hater", "hates", "hauls", "haunt", "haven", "havoc",
    "hawks", "hazel", "heads", "heady", "heals", "heaps", "heard", "heart",
    "heats", "heavy", "hedge", "heeds", "heels", "hefty", "heirs", "heist",
    "helix", "hello", "helps", "hence", "herbs", "herds", "heron", "hertz",
    "highs", "hiked", "hiker", "hikes", "hills", "hilly", "hilts", "hinds",
    "hinge", "hints", "hippo", "hippy", "hired", "hitch", "hoard", "hobby",
    "hoist", "holds", "holes", "holly", "homes", "honey", "honor", "hoods",
    "hooks", "hoped", "hopes", "horns", "horny", "horse", "horsy", "hosed",
    "hoses", "hosts", "hotel", "hotly", "hound", "hours", "house", "hover",
    "howdy", "howls", "hubby", "huffs", "huffy", "human", "humid", "humps",
    "humus", "humor", "humps", "hunks", "hunky", "hunts", "hurry", "hurts",
    "husky", "hutch", "hyena", "hymen", "hymns", "hyped", "hyper",
    # I
    "icier", "icily", "icing", "ideal", "ideas", "idiom", "idiot", "idled",
    "idler", "idols", "igloo", "image", "imbue", "impel", "imply", "inane",
    "inbox", "incur", "index", "indie", "inept", "inert", "infer", "infix",
    "ingot", "inked", "inlay", "inlet", "inner", "input", "inter", "intro",
    "ionic", "irate", "irked", "irony", "issue", "ivory", "ivied",
    # J
    "jab", "jacks", "jaded", "jails", "japes", "jaunt", "jazzy", "jeans",
    "jeers", "jelly", "jerks", "jerky", "jests", "jewel", "jiffy", "jilts",
    "jimmy", "jinks", "jinxs", "jibed", "jibes", "jived", "jives", "jobs",
    "jocks", "joins", "joint", "joker", "jokes", "jolly", "jolts", "joust",
    "judge", "juice", "juicy", "jumbo", "jumps", "jumpy", "junco", "juror",
    "justs", "jutes",
    # K
    "karma", "kayak", "kebab", "keels", "keens", "keeps", "kefir", "kelps",
    "kenaf", "ketch", "kicks", "kills", "kilns", "kilts", "kinds", "kings",
    "kinks", "kinky", "kiosk", "kites", "knack", "knave", "knead", "kneed",
    "kneel", "knees", "knelt", "knife", "knits", "knobs", "knock", "knoll",
    "knots", "known", "knows", "koala", "krill", "kudos",
    # L
    "label", "labor", "laced", "laces", "lacks", "laden", "ladle", "laird",
    "lairs", "lakes", "lambs", "lamed", "lamps", "lance", "lands", "lanes",
    "lanky", "lapel", "lapse", "large", "largo", "larva", "laser", "lasts",
    "latch", "later", "latex", "lathe", "latte", "laugh", "lawns", "layer",
    "leach", "leads", "leafy", "leaks", "leaky", "leant", "leaps", "leapt",
    "learn", "lease", "leash", "least", "leave", "ledge", "leech", "leeks",
    "leery", "legal", "lemma", "lemon", "lemur", "lends", "level", "lever",
    "light", "liked", "liken", "lilac", "limbo", "limbs", "limed", "limes",
    "limey", "limit", "limps", "lined", "linen", "liner", "lines", "lingo",
    "links", "lions", "lipid", "lists", "liter", "lithe", "liver", "lived",
    "liven", "liver", "lives", "livid", "llama", "loads", "loafs", "loams",
    "loamy", "loans", "lobby", "lobes", "local", "locks", "locus", "lodge",
    "lofts", "lofty", "logic", "login", "logos", "loner", "longs", "looks",
    "looms", "loons", "loony", "loops", "loopy", "loose", "loots", "lords",
    "lorry", "loser", "loses", "lossy", "lotus", "lousy", "louse", "loved",
    "lover", "loves", "lower", "lowly", "loyal", "lucid", "lucky", "lulls",
    "lumen", "lumps", "lumpy", "lunar", "lunch", "lunge", "lungs", "lurch",
    "lured", "lures", "lurks", "lusty", "lying", "lymph", "lynch", "lyric",
    # M
    "macho", "macro", "madam", "madly", "mafia", "magic", "magma", "major",
    "maker", "makes", "males", "malls", "malts", "mamas", "mambo", "mango",
    "mania", "manic", "manor", "maple", "march", "mares", "marks", "marsh",
    "masks", "mason", "match", "mated", "mates", "maths", "mauls", "maven",
    "maxed", "maxes", "maxim", "mayor", "maybe", "meals", "means", "meant",
    "meats", "meaty", "media", "medal", "meets", "melee", "melon", "melts",
    "memo", "memos", "mends", "menus", "mercy", "merge", "merit", "merry",
    "meshy", "messy", "metal", "meter", "metro", "micas", "micro", "midst",
    "might", "miles", "milks", "milky", "mills", "mimic", "mince", "minds",
    "mined", "miner", "mines", "minor", "minus", "mirth", "miser", "misty",
    "miter", "mitre", "mitts", "mixed", "mixer", "mixes", "moans", "moats",
    "mocks", "model", "modem", "modes", "mogul", "moist", "molar", "molds",
    "moldy", "moles", "molts", "money", "monks", "month", "moods", "moody",
    "moose", "moral", "morph", "morse", "mossy", "motel", "motif", "motor",
    "motto", "mould", "moult", "mound", "mount", "mourn", "mouse", "mousy",
    "mouth", "moved", "mover", "moves", "movie", "mowed", "mower", "mucus",
    "muddy", "muffs", "mulch", "mules", "mulls", "mumps", "munch", "mural",
    "murky", "mushy", "music", "musky", "musty", "muted", "mutes", "mutts",
    "myrrh", "myths",
    # N
    "nacho", "nadir", "nails", "naive", "naked", "named", "namer", "names",
    "nanny", "napes", "nappy", "nasal", "nasty", "natal", "naval", "navel",
    "necks", "needs", "needy", "nerve", "nervy", "nests", "never", "newer",
    "newly", "nexus", "nicer", "niche", "nifty", "night", "nimby", "ninja",
    "ninth", "noble", "nobly", "nodes", "noise", "noisy", "nomad", "nonce",
    "nooks", "norms", "north", "notch", "noted", "notes", "novel", "nudge",
    "nurse", "nutty", "nylon", "nymph",
    # O
    "oaken", "oasis", "oaths", "occur", "ocean", "octyl", "oddly", "odder",
    "odors", "odour", "offal", "offer", "often", "ogled", "ogler", "ogles",
    "oiled", "oiler", "olive", "omega", "onset", "oomph", "opens", "opera",
    "opium", "opted", "optic", "orbit", "order", "organ", "other", "ought",
    "ounce", "outer", "outdo", "outgo", "ovals", "ovary", "ovate", "ovens",
    "overt", "owing", "owned", "owner", "oxide", "ozone",
    # P
    "paced", "pacer", "paces", "packs", "paddy", "pages", "pails", "pains",
    "paint", "pairs", "paler", "palms", "palsy", "panel", "panes", "pangs",
    "panic", "pansy", "pants", "paper", "parch", "pared", "parka", "parks",
    "parry", "parse", "parts", "party", "paste", "pasta", "pasty", "patch",
    "paths", "patio", "pause", "paved", "paver", "paves", "pawed", "pawns",
    "peace", "peach", "peaks", "pearl", "pears", "pease", "pecan", "pecks",
    "pedal", "peeks", "peels", "peers", "penal", "pence", "penny", "perch",
    "peril", "perks", "perky", "perms", "pesky", "pests", "petal", "petty",
    "phase", "phone", "photo", "piano", "picks", "picky", "piece", "piers",
    "piggy", "piled", "piles", "pills", "pilot", "pimps", "pinch", "pined",
    "pines", "pings", "pinko", "pinks", "pinky", "pinto", "pints", "pious",
    "piped", "piper", "pipes", "pique", "pitch", "piths", "pithy", "piton",
    "pivot", "pixel", "pixie", "pizza", "place", "plaid", "plain", "plait",
    "plane", "plank", "plans", "plant", "plate", "playa", "plaza", "plead",
    "pleas", "pleat", "plied", "plier", "plies", "plods", "plops", "plots",
    "plows", "ploys", "pluck", "plugs", "plumb", "plume", "plump", "plums",
    "plunk", "plush", "poems", "poets", "point", "poise", "poked", "poker",
    "pokes", "polar", "polka", "polls", "polyp", "ponds", "pools", "poops",
    "popes", "poppy", "porch", "pored", "pores", "porks", "porky", "ports",
    "posed", "poser", "poses", "posit", "posse", "posts", "potty", "pouch",
    "pound", "pours", "power", "prams", "prank", "prawn", "prays", "press",
    "preys", "price", "prick", "pride", "pried", "pries", "prime", "primp",
    "prims", "print", "prior", "prism", "privy", "prize", "probe", "prods",
    "proms", "prone", "prong", "proof", "props", "prose", "proud", "prove",
    "prowl", "proxy", "prude", "prune", "psalm", "pubic", "puffy", "pulls",
    "pulps", "pulpy", "pulse", "pumps", "punch", "punks", "punny", "pupil",
    "puppy", "puree", "purge", "purrs", "purse", "pushy", "putts", "putty",
    "pygmy",
    # Q
    "quack", "quaff", "quail", "quake", "qualm", "quart", "quasi", "queen",
    "queer", "quell", "query", "quest", "queue", "quick", "quiet", "quill",
    "quilt", "quirk", "quite", "quota", "quote", "quoth",
    # R
    "rabbi", "rabid", "raced", "racer", "races", "racks", "radar", "radii",
    "radio", "radon", "rafts", "raged", "rages", "raids", "rails", "rains",
    "rainy", "raise", "rally", "ramps", "ranch", "range", "ranks", "rants",
    "rapid", "rated", "rater", "rates", "ratio", "ratty", "raved", "raven",
    "raves", "rawer", "rayon", "razed", "razor", "reach", "react", "reads",
    "ready", "realm", "reams", "reaps", "rears", "rebel", "recap", "recon",
    "recut", "reeds", "reedy", "reefs", "reeks", "reels", "refer", "reign",
    "reins", "relax", "relay", "relic", "remit", "renal", "renew", "rents",
    "repay", "repel", "reply", "rerun", "reset", "resin", "rests", "retro",
    "retry", "revel", "rider", "rides", "ridge", "rifle", "rifts", "right",
    "rigid", "rigor", "riled", "rills", "rinds", "rings", "rinse", "riots",
    "ripen", "riper", "risen", "riser", "rises", "risks", "risky", "rites",
    "rival", "river", "rivet", "roads", "roams", "roars", "roast", "robed",
    "robes", "robin", "robot", "rocks", "rocky", "rogue", "roles", "rolls",
    "roman", "rooms", "roomy", "roost", "roots", "roped", "ropes", "roses",
    "rotor", "rouge", "rough", "round", "rouse", "route", "rowdy", "rowed",
    "rower", "royal", "rugby", "ruins", "ruled", "ruler", "rules", "rumba",
    "rumor", "rumps", "runes", "rungs", "runny", "rupee", "rural", "rushy",
    "rusts", "rusty",
    # S
    "saber", "sable", "sadly", "safes", "sages", "saint", "salad", "sales",
    "salon", "salsa", "salts", "salty", "salve", "salvo", "samba", "sands",
    "sandy", "saner", "sappy", "satin", "satyr", "sauce", "saucy", "sauna",
    "saute", "saved", "saver", "saves", "savor", "savvy", "scale", "scalp",
    "scams", "scant", "scare", "scarf", "scary", "scene", "scent", "schmo",
    "scope", "score", "scorn", "scout", "scowl", "scram", "scrap", "scree",
    "screw", "scrub", "scrum", "scuba", "seals", "seams", "seats", "sedan",
    "seeds", "seedy", "seeks", "seems", "seize", "sense", "sepia", "serif",
    "serum", "serve", "setup", "seven", "sever", "sewed", "sewer", "shade",
    "shady", "shaft", "shake", "shaky", "shall", "shame", "shape", "shard",
    "share", "shark", "sharp", "shave", "shawl", "shear", "sheds", "sheen",
    "sheep", "sheer", "sheet", "shelf", "shell", "shift", "shims", "shine",
    "shins", "shiny", "ships", "shire", "shirk", "shirt", "shock", "shoes",
    "shone", "shook", "shoot", "shops", "shore", "shorn", "short", "shots",
    "shout", "shove", "shown", "shows", "showy", "shrub", "shrug", "shuck",
    "shunt", "sided", "sides", "siege", "sieve", "sighs", "sight", "sigma",
    "signs", "silks", "silky", "silly", "since", "sinew", "sings", "sinks",
    "siren", "sites", "sixth", "sixty", "sized", "sizes", "skate", "skein",
    "skids", "skill", "skimp", "skins", "skull", "skunk", "slabs", "slack",
    "slain", "slang", "slant", "slaps", "slash", "slate", "slats", "slave",
    "slays", "sleds", "sleek", "sleep", "sleet", "slept", "slice", "slick",
    "slide", "slime", "slimy", "sling", "slink", "slips", "slope", "slops",
    "slosh", "sloth", "slots", "slugs", "slump", "slums", "slung", "slunk",
    "slurp", "smack", "small", "smart", "smash", "smear", "smell", "smelt",
    "smile", "smirk", "smite", "smith", "smock", "smoke", "smoky", "snack",
    "snafu", "snags", "snail", "snake", "snaky", "snaps", "snare", "snarl",
    "sneak", "sneer", "sniff", "snipe", "snobs", "snoop", "snore", "snort",
    "snout", "snowy", "snubs", "snuff", "soapy", "soars", "sober", "socks",
    "sofas", "solar", "soled", "soles", "solid", "solos", "solve", "songs",
    "sonic", "sooty", "sorry", "sorts", "souls", "sound", "south", "sowed",
    "sower", "space", "spade", "spans", "spare", "spark", "spasm", "spawn",
    "speak", "spear", "specs", "speed", "spell", "spend", "spent", "spice",
    "spicy", "spied", "spiel", "spies", "spike", "spill", "spine", "spiny",
    "spoke", "spoof", "spook", "spool", "spoon", "spore", "sport", "spots",
    "spout", "spray", "spree", "sprig", "spunk", "spurn", "spurs", "squad",
    "squat", "squid", "stabs", "stack", "staff", "stage", "stags", "staid",
    "stain", "stair", "stake", "stale", "stalk", "stall", "stamp", "stand",
    "stank", "stare", "stark", "stars", "start", "stash", "state", "stays",
    "steak", "steal", "steam", "steel", "steep", "steer", "stems", "steps",
    "stern", "stews", "stick", "stiff", "still", "stilt", "sting", "stink",
    "stint", "stock", "stoic", "stoke", "stole", "stomp", "stone", "stony",
    "stood", "stool", "stoop", "stops", "store", "stork", "storm", "story",
    "stout", "stove", "strap", "straw", "stray", "strip", "strut", "stuck",
    "studs", "study", "stuff", "stump", "stung", "stunk", "stunt", "style",
    "suave", "sucks", "suede", "sugar", "suite", "suits", "sulks", "sulky",
    "sunny", "super", "surge", "surly", "sushi", "swabs", "swamp", "swans",
    "swaps", "swarm", "swath", "sways", "swear", "sweat", "sweep", "sweet",
    "swell", "swept", "swift", "swill", "swine", "swing", "swipe", "swirl",
    "swish", "swiss", "swoop", "swore", "sworn", "swung", "syrup",
    # T
    "tabby", "table", "taboo", "tacit", "tacks", "tacky", "taffy", "tails",
    "taint", "taken", "taker", "takes", "tales", "talks", "tally", "talon",
    "tamed", "tamer", "tames", "tangs", "tangy", "tanks", "tapes", "taper",
    "tapir", "tardy", "tasks", "taste", "tasty", "tatty", "taunt", "tawny",
    "taxes", "taxed", "teach", "teams", "tears", "teary", "tease", "teddy",
    "teems", "teens", "teeth", "tempo", "tends", "tenor", "tense", "tenth",
    "tents", "terms", "tests", "texts", "thank", "theft", "their", "theme",
    "there", "these", "thick", "thief", "thigh", "thing", "think", "third",
    "thorn", "those", "three", "threw", "throw", "thuds", "thugs", "thumb",
    "thump", "tidal", "tides", "tiger", "tight", "tiled", "tiles", "tilts",
    "timer", "times", "timid", "tinge", "tippy", "tipsy", "tired", "titan",
    "tithe", "title", "toast", "today", "toddy", "token", "tolls", "tombs",
    "toned", "toner", "tones", "tongs", "tonic", "tools", "tooth", "topic",
    "topaz", "torch", "total", "totem", "touch", "tough", "tours", "towel",
    "tower", "towns", "toxic", "toxin", "trace", "track", "tract", "trade",
    "trail", "train", "trait", "tramp", "trans", "traps", "trash", "trawl",
    "trays", "treat", "trend", "trial", "tribe", "trick", "tried", "tries",
    "trigs", "trims", "trios", "trips", "trite", "troll", "troop", "trope",
    "troth", "trots", "trout", "trove", "trowl", "truck", "truce", "truly",
    "trump", "trunk", "truss", "trust", "truth", "tulip", "tumor", "tuned",
    "tuner", "tunes", "turbo", "turfs", "turns", "tutor", "twang", "tweak",
    "tweed", "tweet", "twice", "twigs", "twill", "twine", "twirl", "twist",
    "twits", "tying", "typed", "types", "typos",
    # U
    "udder", "ultra", "uncle", "uncut", "under", "undid", "undue", "unfit",
    "union", "unite", "units", "unity", "unlit", "until", "unwed", "upper",
    "upset", "urban", "urged", "usage", "usher", "users", "using", "usual",
    "usurp", "utter",
    # V
    "vague", "valet", "valid", "value", "valve", "vapor", "vault", "vegan",
    "veils", "veins", "venal", "venom", "venue", "verbs", "verge", "verse",
    "vigor", "vigil", "vines", "vinyl", "viola", "viper", "viral", "virus",
    "visor", "visit", "vista", "vital", "vivid", "vixen", "vocal", "vodka",
    "vogue", "voice", "voila", "volts", "voted", "voter", "votes", "vouch",
    "vowel", "vowed",
    # W
    "wacky", "waded", "wader", "wades", "waged", "wager", "wages", "wagon",
    "waifs", "wails", "waist", "waits", "waked", "waken", "wakes", "walks",
    "walls", "waltz", "wands", "wants", "wanna", "wards", "wares", "warns",
    "warps", "warts", "warty", "waste", "watch", "water", "waved", "waver",
    "waves", "waxed", "waxen", "weals", "weans", "wears", "weary", "weave",
    "webby", "wedge", "wedgy", "weeds", "weedy", "weeks", "weigh", "weird",
    "wells", "wench", "whale", "wheat", "wheel", "where", "which", "while",
    "whine", "whiny", "whips", "whirl", "whisk", "white", "whole", "whose",
    "wicks", "wider", "widen", "widow", "width", "wield", "wills", "wince",
    "winch", "winds", "windy", "wined", "wines", "wings", "winks", "wiped",
    "wiper", "wipes", "wired", "wires", "witch", "withs", "witty", "woken",
    "woman", "women", "wombs", "woods", "woody", "words", "wordy", "works",
    "world", "worms", "wormy", "worry", "worse", "worst", "worth", "would",
    "wound", "wrath", "wreak", "wreck", "wrest", "wring", "wrist", "write",
    "wrong", "wrote", "wrung",
    # X
    "xenon", "xerox",
    # Y
    "yacht", "yanks", "yards", "yarns", "yearn", "years", "yeast", "yells",
    "yield", "yokel", "yolks", "young", "yours", "youth", "yucca",
    # Z
    "zappy", "zeals", "zebra", "zippy", "zonal", "zones",
}

# Filter WORDLE_VALID to exactly 5-letter words
WORDLE_VALID = {w for w in WORDLE_VALID if len(w) == 5}

# ---------------------------------------------------------------------------
# 3. DRAW WORDS  (~200 easily drawable words, organized by category)
# ---------------------------------------------------------------------------
DRAW_WORDS = [
    # Animals
    "dog", "cat", "fish", "bird", "frog", "bee", "ant", "bat", "owl",
    "cow", "pig", "hen", "fox", "rat", "ape", "eel", "yak",
    "bear", "deer", "duck", "goat", "lion", "wolf", "moth", "crab",
    "seal", "swan", "toad", "worm", "mole", "hare",
    "horse", "mouse", "whale", "shark", "snail", "snake", "eagle", "camel",
    "koala", "panda", "tiger", "zebra", "llama", "otter",
    "monkey", "parrot", "turtle", "spider", "rabbit", "donkey",
    "penguin", "dolphin", "octopus", "giraffe", "gorilla",
    "elephant", "dinosaur", "kangaroo", "flamingo", "seahorse",
    "jellyfish", "crocodile", "butterfly", "caterpillar",
    "peacock", "lobster", "starfish", "scorpion", "hedgehog",

    # Food & Drink
    "egg", "pie", "jam",
    "cake", "corn", "pear", "rice", "soup", "taco",
    "apple", "bread", "candy", "donut", "grape", "lemon", "melon",
    "olive", "onion", "peach", "pizza", "steak", "sushi",
    "banana", "burger", "carrot", "cheese", "cherry", "cookie",
    "hotdog", "muffin", "noodle", "potato", "pretzel",
    "pancake", "popcorn", "cupcake", "avocado",
    "pineapple", "hamburger", "watermelon", "strawberry",
    "ice cream", "chocolate",

    # Objects & Things
    "key", "cup", "hat", "bed", "box", "bag", "pen",
    "bell", "book", "bomb", "boot", "bowl", "bulb", "comb", "coin",
    "door", "drum", "flag", "fork", "gift", "lamp", "lock", "mask",
    "nail", "ring", "rope", "shoe", "soap", "sock", "star", "tent",
    "vase", "wand",
    "arrow", "broom", "brush", "chair", "chest", "clock", "couch",
    "crown", "fence", "glass", "globe", "knife", "phone", "piano",
    "plate", "purse", "ruler", "sword", "table", "torch", "wheel",
    "anchor", "bucket", "camera", "candle", "guitar", "hammer",
    "ladder", "mirror", "pencil", "pillow", "rocket", "shield",
    "trophy", "wallet",
    "balloon", "battery", "compass", "diamond", "feather",
    "lantern", "magnet", "package", "suitcase",
    "scissors", "telescope", "umbrella", "binoculars",
    "fireworks", "flashlight", "microphone",

    # Nature & Weather
    "sun", "moon", "tree", "leaf", "wave",
    "cloud", "flame", "river", "beach", "plant", "grass",
    "flower", "forest", "island", "desert", "jungle", "cactus",
    "rainbow", "mountain", "mushroom", "volcano", "tornado",
    "campfire", "waterfall", "snowflake", "lightning",

    # Buildings & Vehicles
    "car", "bus", "van",
    "barn", "boat", "ship", "tank", "taxi",
    "cabin", "house", "plane", "train", "truck", "canoe",
    "bridge", "castle", "church", "garage", "igloo", "prison",
    "bicycle", "tractor", "airplane", "windmill", "sailboat",
    "hospital", "submarine", "helicopter", "lighthouse",

    # People & Characters
    "baby", "king", "chef",
    "angel", "clown", "devil", "fairy", "ghost", "nurse",
    "ninja", "pirate", "robot", "witch", "wizard", "zombie",
    "cowboy", "mermaid", "vampire", "princess", "skeleton",
    "snowman", "scarecrow", "superhero", "astronaut",

    # Body Parts
    "eye", "ear",
    "bone", "foot", "hand", "nose", "lips",
    "brain", "heart", "mouth", "skull", "teeth", "thumb", "tongue",

    # Actions / Scenes
    "rain", "fire", "swim",
    "dance", "sleep", "smile", "climb",
    "fishing", "running", "surfing", "reading", "painting",
    "treasure",
]
