// ============================================================================
// EMOJI-DATA.JS — Comprehensive emoji catalog (~450 emojis)
// ============================================================================

var EMOJI_DATA = {
  categories: [
    { id: 'recent',     name: 'Recently Used', icon: '\u{1F550}' },
    { id: 'smileys',    name: 'Smileys',       icon: '\u{1F600}' },
    { id: 'people',     name: 'People',        icon: '\u{1F44B}' },
    { id: 'animals',    name: 'Animals',       icon: '\u{1F436}' },
    { id: 'food',       name: 'Food',          icon: '\u{1F354}' },
    { id: 'activities', name: 'Activities',    icon: '\u26BD' },
    { id: 'travel',     name: 'Travel',        icon: '\u{1F697}' },
    { id: 'objects',    name: 'Objects',       icon: '\u{1F4A1}' },
    { id: 'symbols',    name: 'Symbols',       icon: '\u2764\uFE0F' },
    { id: 'flags',      name: 'Flags',         icon: '\u{1F3C1}' }
  ],
  emojis: [
    // ── Smileys ──
    { char: '😀', name: 'grinning face', keywords: ['happy','smile','grin'], cat: 'smileys' },
    { char: '😃', name: 'grinning face with big eyes', keywords: ['happy','smile'], cat: 'smileys' },
    { char: '😄', name: 'grinning face with smiling eyes', keywords: ['happy','laugh'], cat: 'smileys' },
    { char: '😁', name: 'beaming face', keywords: ['happy','grin','teeth'], cat: 'smileys' },
    { char: '😆', name: 'grinning squinting face', keywords: ['laugh','happy'], cat: 'smileys' },
    { char: '😅', name: 'grinning face with sweat', keywords: ['nervous','laugh','relief'], cat: 'smileys' },
    { char: '🤣', name: 'rolling on the floor laughing', keywords: ['lol','rofl','laugh'], cat: 'smileys' },
    { char: '😂', name: 'face with tears of joy', keywords: ['laugh','cry','lol'], cat: 'smileys' },
    { char: '🙂', name: 'slightly smiling face', keywords: ['smile','ok'], cat: 'smileys' },
    { char: '🙃', name: 'upside-down face', keywords: ['silly','sarcasm'], cat: 'smileys' },
    { char: '😉', name: 'winking face', keywords: ['wink','flirt'], cat: 'smileys' },
    { char: '😊', name: 'smiling face with smiling eyes', keywords: ['happy','blush'], cat: 'smileys' },
    { char: '😇', name: 'smiling face with halo', keywords: ['angel','innocent'], cat: 'smileys' },
    { char: '🥰', name: 'smiling face with hearts', keywords: ['love','adore'], cat: 'smileys' },
    { char: '😍', name: 'heart eyes', keywords: ['love','crush','adore'], cat: 'smileys' },
    { char: '🤩', name: 'star-struck', keywords: ['wow','excited','star'], cat: 'smileys' },
    { char: '😘', name: 'face blowing a kiss', keywords: ['kiss','love'], cat: 'smileys' },
    { char: '😗', name: 'kissing face', keywords: ['kiss','pucker'], cat: 'smileys' },
    { char: '😚', name: 'kissing face with closed eyes', keywords: ['kiss'], cat: 'smileys' },
    { char: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss'], cat: 'smileys' },
    { char: '🥲', name: 'smiling face with tear', keywords: ['happy','sad','bittersweet'], cat: 'smileys' },
    { char: '😋', name: 'face savoring food', keywords: ['yummy','delicious','tongue'], cat: 'smileys' },
    { char: '😛', name: 'face with tongue', keywords: ['tongue','silly'], cat: 'smileys' },
    { char: '😜', name: 'winking face with tongue', keywords: ['silly','tongue','wink'], cat: 'smileys' },
    { char: '🤪', name: 'zany face', keywords: ['crazy','wild','silly'], cat: 'smileys' },
    { char: '😝', name: 'squinting face with tongue', keywords: ['tongue','silly','gross'], cat: 'smileys' },
    { char: '🤑', name: 'money-mouth face', keywords: ['money','rich','dollar'], cat: 'smileys' },
    { char: '🤗', name: 'hugging face', keywords: ['hug','warm'], cat: 'smileys' },
    { char: '🤭', name: 'face with hand over mouth', keywords: ['oops','giggle'], cat: 'smileys' },
    { char: '🤫', name: 'shushing face', keywords: ['quiet','secret','shh'], cat: 'smileys' },
    { char: '🤔', name: 'thinking face', keywords: ['think','hmm','wonder'], cat: 'smileys' },
    { char: '🫡', name: 'saluting face', keywords: ['salute','respect','yes sir'], cat: 'smileys' },
    { char: '🤐', name: 'zipper-mouth face', keywords: ['quiet','secret','zip'], cat: 'smileys' },
    { char: '🤨', name: 'face with raised eyebrow', keywords: ['doubt','skeptical'], cat: 'smileys' },
    { char: '😐', name: 'neutral face', keywords: ['meh','blank'], cat: 'smileys' },
    { char: '😑', name: 'expressionless face', keywords: ['blank','meh'], cat: 'smileys' },
    { char: '😶', name: 'face without mouth', keywords: ['silent','speechless'], cat: 'smileys' },
    { char: '🫠', name: 'melting face', keywords: ['melt','hot','disappear'], cat: 'smileys' },
    { char: '😏', name: 'smirking face', keywords: ['smirk','sly'], cat: 'smileys' },
    { char: '😒', name: 'unamused face', keywords: ['bored','annoyed'], cat: 'smileys' },
    { char: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll','annoyed','whatever'], cat: 'smileys' },
    { char: '😬', name: 'grimacing face', keywords: ['awkward','cringe'], cat: 'smileys' },
    { char: '🤥', name: 'lying face', keywords: ['lie','pinocchio'], cat: 'smileys' },
    { char: '🫨', name: 'shaking face', keywords: ['shake','shock','earthquake'], cat: 'smileys' },
    { char: '😌', name: 'relieved face', keywords: ['calm','relief','peaceful'], cat: 'smileys' },
    { char: '😔', name: 'pensive face', keywords: ['sad','thoughtful'], cat: 'smileys' },
    { char: '😪', name: 'sleepy face', keywords: ['tired','sleepy'], cat: 'smileys' },
    { char: '🤤', name: 'drooling face', keywords: ['drool','hungry','yum'], cat: 'smileys' },
    { char: '😴', name: 'sleeping face', keywords: ['sleep','zzz','tired'], cat: 'smileys' },
    { char: '😷', name: 'face with medical mask', keywords: ['sick','mask','covid'], cat: 'smileys' },
    { char: '🤒', name: 'face with thermometer', keywords: ['sick','fever','ill'], cat: 'smileys' },
    { char: '🤕', name: 'face with head-bandage', keywords: ['hurt','injured'], cat: 'smileys' },
    { char: '🤢', name: 'nauseated face', keywords: ['sick','nausea','gross','vomit'], cat: 'smileys' },
    { char: '🤮', name: 'face vomiting', keywords: ['sick','puke','vomit'], cat: 'smileys' },
    { char: '🥵', name: 'hot face', keywords: ['hot','sweat','heat'], cat: 'smileys' },
    { char: '🥶', name: 'cold face', keywords: ['cold','freezing','ice'], cat: 'smileys' },
    { char: '🥴', name: 'woozy face', keywords: ['drunk','dizzy','tipsy'], cat: 'smileys' },
    { char: '😵', name: 'face with crossed-out eyes', keywords: ['dizzy','dead','shocked'], cat: 'smileys' },
    { char: '😵‍💫', name: 'face with spiral eyes', keywords: ['dizzy','confused','hypnotized'], cat: 'smileys' },
    { char: '🤯', name: 'exploding head', keywords: ['mind blown','shocked','wow'], cat: 'smileys' },
    { char: '🤠', name: 'cowboy hat face', keywords: ['cowboy','western','hat'], cat: 'smileys' },
    { char: '🥳', name: 'partying face', keywords: ['party','celebrate','birthday'], cat: 'smileys' },
    { char: '🥸', name: 'disguised face', keywords: ['disguise','glasses','nose'], cat: 'smileys' },
    { char: '😎', name: 'smiling face with sunglasses', keywords: ['cool','sunglasses'], cat: 'smileys' },
    { char: '🤓', name: 'nerd face', keywords: ['nerd','geek','glasses'], cat: 'smileys' },
    { char: '🧐', name: 'face with monocle', keywords: ['monocle','think','inspect'], cat: 'smileys' },
    { char: '😕', name: 'confused face', keywords: ['confused','unsure'], cat: 'smileys' },
    { char: '🫤', name: 'face with diagonal mouth', keywords: ['unsure','meh','skeptical'], cat: 'smileys' },
    { char: '😟', name: 'worried face', keywords: ['worried','concern'], cat: 'smileys' },
    { char: '🙁', name: 'slightly frowning face', keywords: ['sad','frown'], cat: 'smileys' },
    { char: '😮', name: 'face with open mouth', keywords: ['surprised','wow','oh'], cat: 'smileys' },
    { char: '😯', name: 'hushed face', keywords: ['surprised','quiet'], cat: 'smileys' },
    { char: '😲', name: 'astonished face', keywords: ['shocked','amazed'], cat: 'smileys' },
    { char: '😳', name: 'flushed face', keywords: ['embarrassed','blush'], cat: 'smileys' },
    { char: '🥺', name: 'pleading face', keywords: ['puppy eyes','please','beg'], cat: 'smileys' },
    { char: '🥹', name: 'face holding back tears', keywords: ['cry','emotional','touched'], cat: 'smileys' },
    { char: '😦', name: 'frowning face with open mouth', keywords: ['shock','sad'], cat: 'smileys' },
    { char: '😧', name: 'anguished face', keywords: ['pain','anguish'], cat: 'smileys' },
    { char: '😨', name: 'fearful face', keywords: ['scared','fear'], cat: 'smileys' },
    { char: '😰', name: 'anxious face with sweat', keywords: ['anxious','nervous'], cat: 'smileys' },
    { char: '😥', name: 'sad but relieved face', keywords: ['sad','relief'], cat: 'smileys' },
    { char: '😢', name: 'crying face', keywords: ['cry','sad','tear'], cat: 'smileys' },
    { char: '😭', name: 'loudly crying face', keywords: ['cry','sob','sad'], cat: 'smileys' },
    { char: '😱', name: 'face screaming in fear', keywords: ['scream','horror','scared'], cat: 'smileys' },
    { char: '😖', name: 'confounded face', keywords: ['confused','frustrated'], cat: 'smileys' },
    { char: '😣', name: 'persevering face', keywords: ['struggle','endure'], cat: 'smileys' },
    { char: '😞', name: 'disappointed face', keywords: ['sad','disappointed'], cat: 'smileys' },
    { char: '😓', name: 'downcast face with sweat', keywords: ['sweat','hard work'], cat: 'smileys' },
    { char: '😩', name: 'weary face', keywords: ['tired','exhausted','whine'], cat: 'smileys' },
    { char: '😫', name: 'tired face', keywords: ['tired','exhausted'], cat: 'smileys' },
    { char: '🥱', name: 'yawning face', keywords: ['yawn','bored','tired'], cat: 'smileys' },
    { char: '😤', name: 'face with steam from nose', keywords: ['angry','frustrated','huff'], cat: 'smileys' },
    { char: '😡', name: 'pouting face', keywords: ['angry','mad','rage'], cat: 'smileys' },
    { char: '😠', name: 'angry face', keywords: ['angry','mad'], cat: 'smileys' },
    { char: '🤬', name: 'face with symbols on mouth', keywords: ['swearing','cursing','angry'], cat: 'smileys' },
    { char: '😈', name: 'smiling face with horns', keywords: ['devil','evil','mischief'], cat: 'smileys' },
    { char: '👿', name: 'angry face with horns', keywords: ['devil','angry'], cat: 'smileys' },
    { char: '💀', name: 'skull', keywords: ['dead','death','skeleton'], cat: 'smileys' },
    { char: '☠️', name: 'skull and crossbones', keywords: ['dead','danger','pirate'], cat: 'smileys' },
    { char: '💩', name: 'pile of poo', keywords: ['poop','shit','crap'], cat: 'smileys' },
    { char: '🤡', name: 'clown face', keywords: ['clown','funny','joke'], cat: 'smileys' },
    { char: '👹', name: 'ogre', keywords: ['monster','scary'], cat: 'smileys' },
    { char: '👻', name: 'ghost', keywords: ['ghost','spooky','halloween'], cat: 'smileys' },
    { char: '👽', name: 'alien', keywords: ['alien','ufo','space'], cat: 'smileys' },
    { char: '🤖', name: 'robot', keywords: ['robot','bot','ai'], cat: 'smileys' },
    { char: '😺', name: 'grinning cat', keywords: ['cat','happy'], cat: 'smileys' },
    { char: '😸', name: 'grinning cat with smiling eyes', keywords: ['cat','happy'], cat: 'smileys' },
    { char: '😹', name: 'cat with tears of joy', keywords: ['cat','laugh'], cat: 'smileys' },
    { char: '😻', name: 'heart eyes cat', keywords: ['cat','love'], cat: 'smileys' },
    { char: '🙈', name: 'see-no-evil monkey', keywords: ['monkey','shy','hide'], cat: 'smileys' },
    { char: '🙉', name: 'hear-no-evil monkey', keywords: ['monkey','ignore'], cat: 'smileys' },
    { char: '🙊', name: 'speak-no-evil monkey', keywords: ['monkey','oops','secret'], cat: 'smileys' },

    // ── People ──
    { char: '👋', name: 'waving hand', keywords: ['wave','hello','bye'], cat: 'people' },
    { char: '🤚', name: 'raised back of hand', keywords: ['hand','stop'], cat: 'people' },
    { char: '🖐️', name: 'hand with fingers splayed', keywords: ['hand','high five'], cat: 'people' },
    { char: '✋', name: 'raised hand', keywords: ['hand','stop','high five'], cat: 'people' },
    { char: '🖖', name: 'vulcan salute', keywords: ['spock','star trek'], cat: 'people' },
    { char: '🫱', name: 'rightwards hand', keywords: ['hand','right','reach'], cat: 'people' },
    { char: '🫲', name: 'leftwards hand', keywords: ['hand','left','reach'], cat: 'people' },
    { char: '👌', name: 'OK hand', keywords: ['ok','perfect','good'], cat: 'people' },
    { char: '🤌', name: 'pinched fingers', keywords: ['italian','chef kiss','what'], cat: 'people' },
    { char: '🤏', name: 'pinching hand', keywords: ['small','tiny','little'], cat: 'people' },
    { char: '✌️', name: 'victory hand', keywords: ['peace','victory','two'], cat: 'people' },
    { char: '🤞', name: 'crossed fingers', keywords: ['luck','hope','wish'], cat: 'people' },
    { char: '🫰', name: 'hand with index finger and thumb crossed', keywords: ['money','snap','love'], cat: 'people' },
    { char: '🤟', name: 'love-you gesture', keywords: ['love','rock','ily'], cat: 'people' },
    { char: '🤘', name: 'sign of the horns', keywords: ['rock','metal','devil'], cat: 'people' },
    { char: '🤙', name: 'call me hand', keywords: ['call','shaka','hang loose'], cat: 'people' },
    { char: '👈', name: 'backhand index pointing left', keywords: ['left','point'], cat: 'people' },
    { char: '👉', name: 'backhand index pointing right', keywords: ['right','point'], cat: 'people' },
    { char: '👆', name: 'backhand index pointing up', keywords: ['up','point'], cat: 'people' },
    { char: '🖕', name: 'middle finger', keywords: ['finger','rude','flip off'], cat: 'people' },
    { char: '👇', name: 'backhand index pointing down', keywords: ['down','point'], cat: 'people' },
    { char: '☝️', name: 'index pointing up', keywords: ['up','point','one'], cat: 'people' },
    { char: '🫵', name: 'index pointing at the viewer', keywords: ['you','point'], cat: 'people' },
    { char: '👍', name: 'thumbs up', keywords: ['like','yes','good','approve'], cat: 'people' },
    { char: '👎', name: 'thumbs down', keywords: ['dislike','no','bad'], cat: 'people' },
    { char: '✊', name: 'raised fist', keywords: ['fist','power','solidarity'], cat: 'people' },
    { char: '👊', name: 'oncoming fist', keywords: ['punch','fist bump'], cat: 'people' },
    { char: '🤛', name: 'left-facing fist', keywords: ['fist bump'], cat: 'people' },
    { char: '🤜', name: 'right-facing fist', keywords: ['fist bump'], cat: 'people' },
    { char: '👏', name: 'clapping hands', keywords: ['clap','applause','bravo'], cat: 'people' },
    { char: '🙌', name: 'raising hands', keywords: ['celebration','hooray','yay'], cat: 'people' },
    { char: '🫶', name: 'heart hands', keywords: ['heart','love','hands'], cat: 'people' },
    { char: '👐', name: 'open hands', keywords: ['hands','jazz'], cat: 'people' },
    { char: '🤲', name: 'palms up together', keywords: ['pray','hands','please'], cat: 'people' },
    { char: '🤝', name: 'handshake', keywords: ['deal','agreement','shake'], cat: 'people' },
    { char: '🙏', name: 'folded hands', keywords: ['pray','please','thank you'], cat: 'people' },
    { char: '✍️', name: 'writing hand', keywords: ['write','pen','note'], cat: 'people' },
    { char: '💅', name: 'nail polish', keywords: ['nails','beauty','sassy'], cat: 'people' },
    { char: '🤳', name: 'selfie', keywords: ['selfie','phone','camera'], cat: 'people' },
    { char: '💪', name: 'flexed biceps', keywords: ['strong','muscle','flex'], cat: 'people' },
    { char: '🦵', name: 'leg', keywords: ['leg','kick'], cat: 'people' },
    { char: '🦶', name: 'foot', keywords: ['foot','kick','stomp'], cat: 'people' },
    { char: '👀', name: 'eyes', keywords: ['look','see','eyes','stare'], cat: 'people' },
    { char: '👁️', name: 'eye', keywords: ['eye','look'], cat: 'people' },
    { char: '👅', name: 'tongue', keywords: ['tongue','lick','taste'], cat: 'people' },
    { char: '👄', name: 'mouth', keywords: ['lips','mouth','kiss'], cat: 'people' },
    { char: '🫦', name: 'biting lip', keywords: ['lip','bite','nervous','flirt'], cat: 'people' },
    { char: '👶', name: 'baby', keywords: ['baby','child','infant'], cat: 'people' },
    { char: '👧', name: 'girl', keywords: ['girl','child','female'], cat: 'people' },
    { char: '👦', name: 'boy', keywords: ['boy','child','male'], cat: 'people' },
    { char: '👩', name: 'woman', keywords: ['woman','female','adult'], cat: 'people' },
    { char: '👨', name: 'man', keywords: ['man','male','adult'], cat: 'people' },
    { char: '🧑', name: 'person', keywords: ['person','adult'], cat: 'people' },
    { char: '👴', name: 'old man', keywords: ['grandpa','elderly'], cat: 'people' },
    { char: '👵', name: 'old woman', keywords: ['grandma','elderly'], cat: 'people' },
    { char: '🙅', name: 'person gesturing no', keywords: ['no','stop','cross'], cat: 'people' },
    { char: '🙆', name: 'person gesturing OK', keywords: ['ok','yes'], cat: 'people' },
    { char: '💁', name: 'person tipping hand', keywords: ['sassy','information'], cat: 'people' },
    { char: '🙋', name: 'person raising hand', keywords: ['hand','question','hi'], cat: 'people' },
    { char: '🤦', name: 'person facepalming', keywords: ['facepalm','disbelief'], cat: 'people' },
    { char: '🤷', name: 'person shrugging', keywords: ['shrug','idk','whatever'], cat: 'people' },
    { char: '🧏', name: 'deaf person', keywords: ['deaf','ear','hearing'], cat: 'people' },
    { char: '🙇', name: 'person bowing', keywords: ['bow','sorry','respect'], cat: 'people' },
    { char: '💆', name: 'person getting massage', keywords: ['massage','relax','spa'], cat: 'people' },
    { char: '🧖', name: 'person in steamy room', keywords: ['sauna','steam','spa'], cat: 'people' },
    { char: '💃', name: 'woman dancing', keywords: ['dance','party','salsa'], cat: 'people' },
    { char: '🕺', name: 'man dancing', keywords: ['dance','party','disco'], cat: 'people' },
    { char: '👯', name: 'people with bunny ears', keywords: ['party','dance','bunny'], cat: 'people' },
    { char: '🧑‍🤝‍🧑', name: 'people holding hands', keywords: ['couple','together','friends'], cat: 'people' },
    { char: '👫', name: 'woman and man holding hands', keywords: ['couple','date'], cat: 'people' },
    { char: '💏', name: 'kiss', keywords: ['kiss','couple','love'], cat: 'people' },
    { char: '💑', name: 'couple with heart', keywords: ['love','couple','romance'], cat: 'people' },
    { char: '👪', name: 'family', keywords: ['family','parents','child'], cat: 'people' },

    // ── Animals ──
    { char: '🐶', name: 'dog face', keywords: ['dog','puppy','pet'], cat: 'animals' },
    { char: '🐱', name: 'cat face', keywords: ['cat','kitten','pet'], cat: 'animals' },
    { char: '🐭', name: 'mouse face', keywords: ['mouse','rat'], cat: 'animals' },
    { char: '🐹', name: 'hamster', keywords: ['hamster','pet'], cat: 'animals' },
    { char: '🐰', name: 'rabbit face', keywords: ['rabbit','bunny'], cat: 'animals' },
    { char: '🦊', name: 'fox', keywords: ['fox','clever'], cat: 'animals' },
    { char: '🐻', name: 'bear', keywords: ['bear','teddy'], cat: 'animals' },
    { char: '🐼', name: 'panda', keywords: ['panda','bear'], cat: 'animals' },
    { char: '🐨', name: 'koala', keywords: ['koala','cute'], cat: 'animals' },
    { char: '🐯', name: 'tiger face', keywords: ['tiger','cat'], cat: 'animals' },
    { char: '🦁', name: 'lion', keywords: ['lion','king'], cat: 'animals' },
    { char: '🐮', name: 'cow face', keywords: ['cow','moo'], cat: 'animals' },
    { char: '🐷', name: 'pig face', keywords: ['pig','oink'], cat: 'animals' },
    { char: '🐸', name: 'frog', keywords: ['frog','toad'], cat: 'animals' },
    { char: '🐵', name: 'monkey face', keywords: ['monkey','ape'], cat: 'animals' },
    { char: '🐔', name: 'chicken', keywords: ['chicken','hen'], cat: 'animals' },
    { char: '🐧', name: 'penguin', keywords: ['penguin','cold'], cat: 'animals' },
    { char: '🐦', name: 'bird', keywords: ['bird','tweet'], cat: 'animals' },
    { char: '🐤', name: 'baby chick', keywords: ['chick','baby','bird'], cat: 'animals' },
    { char: '🦆', name: 'duck', keywords: ['duck','quack'], cat: 'animals' },
    { char: '🦅', name: 'eagle', keywords: ['eagle','bird','america'], cat: 'animals' },
    { char: '🦉', name: 'owl', keywords: ['owl','wise'], cat: 'animals' },
    { char: '🦇', name: 'bat', keywords: ['bat','vampire'], cat: 'animals' },
    { char: '🐺', name: 'wolf', keywords: ['wolf','howl'], cat: 'animals' },
    { char: '🐗', name: 'boar', keywords: ['boar','pig','wild'], cat: 'animals' },
    { char: '🐴', name: 'horse face', keywords: ['horse','pony'], cat: 'animals' },
    { char: '🦄', name: 'unicorn', keywords: ['unicorn','magic','fantasy'], cat: 'animals' },
    { char: '🐝', name: 'honeybee', keywords: ['bee','honey','buzz'], cat: 'animals' },
    { char: '🪱', name: 'worm', keywords: ['worm','bug'], cat: 'animals' },
    { char: '🐛', name: 'bug', keywords: ['bug','caterpillar'], cat: 'animals' },
    { char: '🦋', name: 'butterfly', keywords: ['butterfly','pretty'], cat: 'animals' },
    { char: '🐌', name: 'snail', keywords: ['snail','slow'], cat: 'animals' },
    { char: '🐞', name: 'ladybug', keywords: ['ladybug','bug'], cat: 'animals' },
    { char: '🐜', name: 'ant', keywords: ['ant','bug'], cat: 'animals' },
    { char: '🐢', name: 'turtle', keywords: ['turtle','slow','shell'], cat: 'animals' },
    { char: '🐍', name: 'snake', keywords: ['snake','hiss'], cat: 'animals' },
    { char: '🦎', name: 'lizard', keywords: ['lizard','reptile'], cat: 'animals' },
    { char: '🦂', name: 'scorpion', keywords: ['scorpion','sting'], cat: 'animals' },
    { char: '🕷️', name: 'spider', keywords: ['spider','web'], cat: 'animals' },
    { char: '🐙', name: 'octopus', keywords: ['octopus','tentacle'], cat: 'animals' },
    { char: '🦑', name: 'squid', keywords: ['squid','ocean'], cat: 'animals' },
    { char: '🦐', name: 'shrimp', keywords: ['shrimp','prawn'], cat: 'animals' },
    { char: '🦀', name: 'crab', keywords: ['crab','beach'], cat: 'animals' },
    { char: '🐡', name: 'blowfish', keywords: ['blowfish','puffer'], cat: 'animals' },
    { char: '🐠', name: 'tropical fish', keywords: ['fish','tropical'], cat: 'animals' },
    { char: '🐟', name: 'fish', keywords: ['fish','ocean'], cat: 'animals' },
    { char: '🐬', name: 'dolphin', keywords: ['dolphin','ocean'], cat: 'animals' },
    { char: '🐳', name: 'spouting whale', keywords: ['whale','ocean'], cat: 'animals' },
    { char: '🦈', name: 'shark', keywords: ['shark','ocean','danger'], cat: 'animals' },
    { char: '🐊', name: 'crocodile', keywords: ['crocodile','alligator'], cat: 'animals' },
    { char: '🐘', name: 'elephant', keywords: ['elephant','big'], cat: 'animals' },
    { char: '🦬', name: 'bison', keywords: ['bison','buffalo'], cat: 'animals' },
    { char: '🦛', name: 'hippopotamus', keywords: ['hippo','river'], cat: 'animals' },
    { char: '🦏', name: 'rhinoceros', keywords: ['rhino','horn'], cat: 'animals' },
    { char: '🐪', name: 'camel', keywords: ['camel','desert','hump'], cat: 'animals' },
    { char: '🦒', name: 'giraffe', keywords: ['giraffe','tall'], cat: 'animals' },
    { char: '🦘', name: 'kangaroo', keywords: ['kangaroo','australia'], cat: 'animals' },
    { char: '🐾', name: 'paw prints', keywords: ['paw','pet','animal','tracks'], cat: 'animals' },
    { char: '🌸', name: 'cherry blossom', keywords: ['flower','spring','sakura'], cat: 'animals' },
    { char: '🌹', name: 'rose', keywords: ['flower','love','red'], cat: 'animals' },
    { char: '🌻', name: 'sunflower', keywords: ['flower','sun','yellow'], cat: 'animals' },
    { char: '🌺', name: 'hibiscus', keywords: ['flower','tropical'], cat: 'animals' },
    { char: '🌷', name: 'tulip', keywords: ['flower','spring'], cat: 'animals' },
    { char: '🌱', name: 'seedling', keywords: ['plant','grow','sprout'], cat: 'animals' },
    { char: '🌲', name: 'evergreen tree', keywords: ['tree','pine','forest'], cat: 'animals' },
    { char: '🌳', name: 'deciduous tree', keywords: ['tree','forest'], cat: 'animals' },
    { char: '🌵', name: 'cactus', keywords: ['cactus','desert'], cat: 'animals' },
    { char: '🍀', name: 'four leaf clover', keywords: ['clover','luck','lucky','shamrock'], cat: 'animals' },
    { char: '🍄', name: 'mushroom', keywords: ['mushroom','toadstool'], cat: 'animals' },

    // ── Food ──
    { char: '🍎', name: 'red apple', keywords: ['apple','fruit','red'], cat: 'food' },
    { char: '🍊', name: 'tangerine', keywords: ['orange','fruit'], cat: 'food' },
    { char: '🍋', name: 'lemon', keywords: ['lemon','citrus','yellow'], cat: 'food' },
    { char: '🍌', name: 'banana', keywords: ['banana','fruit'], cat: 'food' },
    { char: '🍉', name: 'watermelon', keywords: ['watermelon','summer','fruit'], cat: 'food' },
    { char: '🍇', name: 'grapes', keywords: ['grapes','wine','fruit'], cat: 'food' },
    { char: '🍓', name: 'strawberry', keywords: ['strawberry','berry','fruit'], cat: 'food' },
    { char: '🫐', name: 'blueberries', keywords: ['blueberry','berry','fruit'], cat: 'food' },
    { char: '🍑', name: 'peach', keywords: ['peach','fruit','butt'], cat: 'food' },
    { char: '🥭', name: 'mango', keywords: ['mango','tropical','fruit'], cat: 'food' },
    { char: '🍍', name: 'pineapple', keywords: ['pineapple','fruit'], cat: 'food' },
    { char: '🥥', name: 'coconut', keywords: ['coconut','tropical'], cat: 'food' },
    { char: '🥝', name: 'kiwi fruit', keywords: ['kiwi','fruit'], cat: 'food' },
    { char: '🍅', name: 'tomato', keywords: ['tomato','vegetable'], cat: 'food' },
    { char: '🥑', name: 'avocado', keywords: ['avocado','guac','green'], cat: 'food' },
    { char: '🌽', name: 'ear of corn', keywords: ['corn','maize'], cat: 'food' },
    { char: '🌶️', name: 'hot pepper', keywords: ['pepper','hot','spicy'], cat: 'food' },
    { char: '🥒', name: 'cucumber', keywords: ['cucumber','pickle'], cat: 'food' },
    { char: '🥬', name: 'leafy green', keywords: ['lettuce','salad','vegetable'], cat: 'food' },
    { char: '🥦', name: 'broccoli', keywords: ['broccoli','vegetable','green'], cat: 'food' },
    { char: '🧄', name: 'garlic', keywords: ['garlic','cook'], cat: 'food' },
    { char: '🧅', name: 'onion', keywords: ['onion','cry'], cat: 'food' },
    { char: '🥔', name: 'potato', keywords: ['potato','fries'], cat: 'food' },
    { char: '🥐', name: 'croissant', keywords: ['croissant','bread','french'], cat: 'food' },
    { char: '🍞', name: 'bread', keywords: ['bread','loaf','toast'], cat: 'food' },
    { char: '🥖', name: 'baguette bread', keywords: ['baguette','bread','french'], cat: 'food' },
    { char: '🥨', name: 'pretzel', keywords: ['pretzel','snack'], cat: 'food' },
    { char: '🧀', name: 'cheese wedge', keywords: ['cheese','dairy'], cat: 'food' },
    { char: '🥚', name: 'egg', keywords: ['egg','breakfast'], cat: 'food' },
    { char: '🍳', name: 'cooking', keywords: ['egg','frying','breakfast'], cat: 'food' },
    { char: '🥞', name: 'pancakes', keywords: ['pancake','breakfast','maple'], cat: 'food' },
    { char: '🧇', name: 'waffle', keywords: ['waffle','breakfast'], cat: 'food' },
    { char: '🥓', name: 'bacon', keywords: ['bacon','meat','breakfast'], cat: 'food' },
    { char: '🍔', name: 'hamburger', keywords: ['burger','fast food','meat'], cat: 'food' },
    { char: '🍟', name: 'french fries', keywords: ['fries','fast food','chips'], cat: 'food' },
    { char: '🍕', name: 'pizza', keywords: ['pizza','slice','cheese'], cat: 'food' },
    { char: '🌭', name: 'hot dog', keywords: ['hot dog','sausage'], cat: 'food' },
    { char: '🥪', name: 'sandwich', keywords: ['sandwich','bread','lunch'], cat: 'food' },
    { char: '🌮', name: 'taco', keywords: ['taco','mexican'], cat: 'food' },
    { char: '🌯', name: 'burrito', keywords: ['burrito','wrap','mexican'], cat: 'food' },
    { char: '🫔', name: 'tamale', keywords: ['tamale','mexican'], cat: 'food' },
    { char: '🥗', name: 'green salad', keywords: ['salad','healthy','bowl'], cat: 'food' },
    { char: '🍝', name: 'spaghetti', keywords: ['pasta','noodles','italian'], cat: 'food' },
    { char: '🍜', name: 'steaming bowl', keywords: ['ramen','noodles','soup'], cat: 'food' },
    { char: '🍲', name: 'pot of food', keywords: ['stew','soup','cook'], cat: 'food' },
    { char: '🍛', name: 'curry rice', keywords: ['curry','rice','indian'], cat: 'food' },
    { char: '🍣', name: 'sushi', keywords: ['sushi','japanese','fish'], cat: 'food' },
    { char: '🍱', name: 'bento box', keywords: ['bento','japanese','lunch'], cat: 'food' },
    { char: '🥟', name: 'dumpling', keywords: ['dumpling','dim sum','chinese'], cat: 'food' },
    { char: '🍦', name: 'soft ice cream', keywords: ['ice cream','dessert','cone'], cat: 'food' },
    { char: '🍧', name: 'shaved ice', keywords: ['ice','snow cone','dessert'], cat: 'food' },
    { char: '🍨', name: 'ice cream', keywords: ['ice cream','sundae','dessert'], cat: 'food' },
    { char: '🍩', name: 'doughnut', keywords: ['donut','sweet','dessert'], cat: 'food' },
    { char: '🍪', name: 'cookie', keywords: ['cookie','sweet','biscuit'], cat: 'food' },
    { char: '🎂', name: 'birthday cake', keywords: ['cake','birthday','candle'], cat: 'food' },
    { char: '🍰', name: 'shortcake', keywords: ['cake','dessert','sweet'], cat: 'food' },
    { char: '🧁', name: 'cupcake', keywords: ['cupcake','muffin','sweet'], cat: 'food' },
    { char: '🍫', name: 'chocolate bar', keywords: ['chocolate','candy','sweet'], cat: 'food' },
    { char: '🍬', name: 'candy', keywords: ['candy','sweet','sugar'], cat: 'food' },
    { char: '🍭', name: 'lollipop', keywords: ['lollipop','candy','sweet'], cat: 'food' },
    { char: '☕', name: 'hot beverage', keywords: ['coffee','tea','hot','drink'], cat: 'food' },
    { char: '🍵', name: 'teacup without handle', keywords: ['tea','matcha','drink'], cat: 'food' },
    { char: '🧃', name: 'beverage box', keywords: ['juice box','drink'], cat: 'food' },
    { char: '🥤', name: 'cup with straw', keywords: ['soda','drink','straw'], cat: 'food' },
    { char: '🧋', name: 'bubble tea', keywords: ['boba','bubble tea','drink'], cat: 'food' },
    { char: '🍺', name: 'beer mug', keywords: ['beer','drink','alcohol'], cat: 'food' },
    { char: '🍻', name: 'clinking beer mugs', keywords: ['beer','cheers','toast'], cat: 'food' },
    { char: '🥂', name: 'clinking glasses', keywords: ['champagne','cheers','toast'], cat: 'food' },
    { char: '🍷', name: 'wine glass', keywords: ['wine','drink','alcohol'], cat: 'food' },
    { char: '🍸', name: 'cocktail glass', keywords: ['cocktail','martini','drink'], cat: 'food' },
    { char: '🍹', name: 'tropical drink', keywords: ['tropical','cocktail','drink'], cat: 'food' },

    // ── Activities ──
    { char: '⚽', name: 'soccer ball', keywords: ['soccer','football','sport'], cat: 'activities' },
    { char: '🏀', name: 'basketball', keywords: ['basketball','sport','nba'], cat: 'activities' },
    { char: '🏈', name: 'american football', keywords: ['football','nfl','sport'], cat: 'activities' },
    { char: '⚾', name: 'baseball', keywords: ['baseball','sport','mlb'], cat: 'activities' },
    { char: '🥎', name: 'softball', keywords: ['softball','sport'], cat: 'activities' },
    { char: '🎾', name: 'tennis', keywords: ['tennis','sport','racket'], cat: 'activities' },
    { char: '🏐', name: 'volleyball', keywords: ['volleyball','sport'], cat: 'activities' },
    { char: '🏉', name: 'rugby football', keywords: ['rugby','sport'], cat: 'activities' },
    { char: '🥏', name: 'flying disc', keywords: ['frisbee','disc'], cat: 'activities' },
    { char: '🎱', name: 'pool 8 ball', keywords: ['pool','billiards','8 ball'], cat: 'activities' },
    { char: '🏓', name: 'ping pong', keywords: ['ping pong','table tennis'], cat: 'activities' },
    { char: '🏸', name: 'badminton', keywords: ['badminton','shuttlecock'], cat: 'activities' },
    { char: '🏒', name: 'ice hockey', keywords: ['hockey','ice','nhl'], cat: 'activities' },
    { char: '🥊', name: 'boxing glove', keywords: ['boxing','fight','punch'], cat: 'activities' },
    { char: '🥋', name: 'martial arts uniform', keywords: ['karate','martial arts'], cat: 'activities' },
    { char: '⛳', name: 'flag in hole', keywords: ['golf','sport'], cat: 'activities' },
    { char: '🎣', name: 'fishing pole', keywords: ['fishing','fish'], cat: 'activities' },
    { char: '🎿', name: 'skis', keywords: ['ski','skiing','snow','winter'], cat: 'activities' },
    { char: '🏂', name: 'snowboarder', keywords: ['snowboard','snow','winter'], cat: 'activities' },
    { char: '🏋️', name: 'person lifting weights', keywords: ['gym','weights','fitness'], cat: 'activities' },
    { char: '🚴', name: 'person biking', keywords: ['bike','cycling','bicycle'], cat: 'activities' },
    { char: '🏊', name: 'person swimming', keywords: ['swim','swimming','pool'], cat: 'activities' },
    { char: '🧗', name: 'person climbing', keywords: ['climb','rock','mountain'], cat: 'activities' },
    { char: '🏆', name: 'trophy', keywords: ['trophy','winner','champion','gold'], cat: 'activities' },
    { char: '🥇', name: 'gold medal', keywords: ['gold','first','winner'], cat: 'activities' },
    { char: '🥈', name: 'silver medal', keywords: ['silver','second'], cat: 'activities' },
    { char: '🥉', name: 'bronze medal', keywords: ['bronze','third'], cat: 'activities' },
    { char: '🎮', name: 'video game', keywords: ['game','controller','gaming'], cat: 'activities' },
    { char: '🕹️', name: 'joystick', keywords: ['joystick','game','arcade'], cat: 'activities' },
    { char: '🎲', name: 'game die', keywords: ['dice','game','random'], cat: 'activities' },
    { char: '♟️', name: 'chess pawn', keywords: ['chess','game','strategy'], cat: 'activities' },
    { char: '🎯', name: 'bullseye', keywords: ['target','dart','bullseye'], cat: 'activities' },
    { char: '🎳', name: 'bowling', keywords: ['bowling','strike'], cat: 'activities' },
    { char: '🎭', name: 'performing arts', keywords: ['theater','drama','masks'], cat: 'activities' },
    { char: '🎨', name: 'artist palette', keywords: ['art','paint','draw'], cat: 'activities' },
    { char: '🎬', name: 'clapper board', keywords: ['movie','film','cinema'], cat: 'activities' },
    { char: '🎤', name: 'microphone', keywords: ['mic','karaoke','sing'], cat: 'activities' },
    { char: '🎧', name: 'headphone', keywords: ['headphones','music','listen'], cat: 'activities' },
    { char: '🎵', name: 'musical note', keywords: ['music','note','song'], cat: 'activities' },
    { char: '🎶', name: 'musical notes', keywords: ['music','notes','song'], cat: 'activities' },
    { char: '🎸', name: 'guitar', keywords: ['guitar','music','rock'], cat: 'activities' },
    { char: '🎹', name: 'musical keyboard', keywords: ['piano','keyboard','music'], cat: 'activities' },
    { char: '🥁', name: 'drum', keywords: ['drum','music','beat'], cat: 'activities' },
    { char: '🎪', name: 'circus tent', keywords: ['circus','tent','carnival'], cat: 'activities' },

    // ── Travel ──
    { char: '🚗', name: 'automobile', keywords: ['car','drive','vehicle'], cat: 'travel' },
    { char: '🚕', name: 'taxi', keywords: ['taxi','cab','ride'], cat: 'travel' },
    { char: '🚌', name: 'bus', keywords: ['bus','public transport'], cat: 'travel' },
    { char: '🚑', name: 'ambulance', keywords: ['ambulance','emergency','hospital'], cat: 'travel' },
    { char: '🚒', name: 'fire engine', keywords: ['fire truck','emergency'], cat: 'travel' },
    { char: '🚓', name: 'police car', keywords: ['police','cop','emergency'], cat: 'travel' },
    { char: '🏎️', name: 'racing car', keywords: ['race','fast','speed'], cat: 'travel' },
    { char: '🚲', name: 'bicycle', keywords: ['bike','cycle','ride'], cat: 'travel' },
    { char: '🛵', name: 'motor scooter', keywords: ['scooter','moped'], cat: 'travel' },
    { char: '🏍️', name: 'motorcycle', keywords: ['motorcycle','bike'], cat: 'travel' },
    { char: '✈️', name: 'airplane', keywords: ['plane','flight','travel'], cat: 'travel' },
    { char: '🚀', name: 'rocket', keywords: ['rocket','space','launch'], cat: 'travel' },
    { char: '🛸', name: 'flying saucer', keywords: ['ufo','alien','spaceship'], cat: 'travel' },
    { char: '🚁', name: 'helicopter', keywords: ['helicopter','fly'], cat: 'travel' },
    { char: '🛶', name: 'canoe', keywords: ['canoe','kayak','paddle'], cat: 'travel' },
    { char: '⛵', name: 'sailboat', keywords: ['boat','sail','ocean'], cat: 'travel' },
    { char: '🚢', name: 'ship', keywords: ['ship','boat','cruise'], cat: 'travel' },
    { char: '🚂', name: 'locomotive', keywords: ['train','steam'], cat: 'travel' },
    { char: '🚃', name: 'railway car', keywords: ['train','car'], cat: 'travel' },
    { char: '🏠', name: 'house', keywords: ['house','home'], cat: 'travel' },
    { char: '🏡', name: 'house with garden', keywords: ['house','garden','home'], cat: 'travel' },
    { char: '🏢', name: 'office building', keywords: ['office','building','work'], cat: 'travel' },
    { char: '🏥', name: 'hospital', keywords: ['hospital','medical'], cat: 'travel' },
    { char: '🏫', name: 'school', keywords: ['school','education'], cat: 'travel' },
    { char: '🏰', name: 'castle', keywords: ['castle','princess','medieval'], cat: 'travel' },
    { char: '⛪', name: 'church', keywords: ['church','religion'], cat: 'travel' },
    { char: '🕌', name: 'mosque', keywords: ['mosque','islam','religion'], cat: 'travel' },
    { char: '🗽', name: 'Statue of Liberty', keywords: ['statue','liberty','nyc','america'], cat: 'travel' },
    { char: '🗼', name: 'Tokyo tower', keywords: ['tower','tokyo','japan'], cat: 'travel' },
    { char: '🌍', name: 'globe Europe-Africa', keywords: ['earth','world','globe'], cat: 'travel' },
    { char: '🌎', name: 'globe Americas', keywords: ['earth','world','globe','america'], cat: 'travel' },
    { char: '🌏', name: 'globe Asia-Australia', keywords: ['earth','world','globe','asia'], cat: 'travel' },
    { char: '🌙', name: 'crescent moon', keywords: ['moon','night','sleep'], cat: 'travel' },
    { char: '🌞', name: 'sun with face', keywords: ['sun','sunny','warm'], cat: 'travel' },
    { char: '⭐', name: 'star', keywords: ['star','favorite','night'], cat: 'travel' },
    { char: '🌟', name: 'glowing star', keywords: ['star','sparkle','shine'], cat: 'travel' },
    { char: '⚡', name: 'high voltage', keywords: ['lightning','electric','thunder'], cat: 'travel' },
    { char: '🔥', name: 'fire', keywords: ['fire','hot','flame','lit'], cat: 'travel' },
    { char: '🌈', name: 'rainbow', keywords: ['rainbow','pride','color'], cat: 'travel' },
    { char: '☀️', name: 'sun', keywords: ['sun','sunny','weather'], cat: 'travel' },
    { char: '🌤️', name: 'sun behind small cloud', keywords: ['weather','partly cloudy'], cat: 'travel' },
    { char: '⛅', name: 'sun behind cloud', keywords: ['weather','cloudy'], cat: 'travel' },
    { char: '🌧️', name: 'cloud with rain', keywords: ['rain','weather'], cat: 'travel' },
    { char: '❄️', name: 'snowflake', keywords: ['snow','cold','winter','ice'], cat: 'travel' },
    { char: '⛄', name: 'snowman', keywords: ['snowman','winter','cold'], cat: 'travel' },
    { char: '🌊', name: 'water wave', keywords: ['wave','ocean','surf'], cat: 'travel' },

    // ── Objects ──
    { char: '👓', name: 'glasses', keywords: ['glasses','eyeglasses','specs'], cat: 'objects' },
    { char: '🕶️', name: 'sunglasses', keywords: ['sunglasses','cool','shades'], cat: 'objects' },
    { char: '👑', name: 'crown', keywords: ['crown','king','queen','royal'], cat: 'objects' },
    { char: '🎩', name: 'top hat', keywords: ['hat','fancy','gentleman'], cat: 'objects' },
    { char: '💍', name: 'ring', keywords: ['ring','wedding','engaged','diamond'], cat: 'objects' },
    { char: '💎', name: 'gem stone', keywords: ['diamond','gem','jewel'], cat: 'objects' },
    { char: '📱', name: 'mobile phone', keywords: ['phone','cell','mobile'], cat: 'objects' },
    { char: '💻', name: 'laptop', keywords: ['laptop','computer','pc'], cat: 'objects' },
    { char: '⌨️', name: 'keyboard', keywords: ['keyboard','type'], cat: 'objects' },
    { char: '🖥️', name: 'desktop computer', keywords: ['computer','desktop','monitor'], cat: 'objects' },
    { char: '📷', name: 'camera', keywords: ['camera','photo','picture'], cat: 'objects' },
    { char: '📹', name: 'video camera', keywords: ['video','camera','film'], cat: 'objects' },
    { char: '📺', name: 'television', keywords: ['tv','television','watch'], cat: 'objects' },
    { char: '📻', name: 'radio', keywords: ['radio','music','listen'], cat: 'objects' },
    { char: '🔔', name: 'bell', keywords: ['bell','notification','alert'], cat: 'objects' },
    { char: '🔕', name: 'bell with slash', keywords: ['mute','silent','bell'], cat: 'objects' },
    { char: '📢', name: 'loudspeaker', keywords: ['speaker','announce','loud'], cat: 'objects' },
    { char: '💡', name: 'light bulb', keywords: ['idea','light','bulb'], cat: 'objects' },
    { char: '🔦', name: 'flashlight', keywords: ['flashlight','torch','light'], cat: 'objects' },
    { char: '🔑', name: 'key', keywords: ['key','lock','password'], cat: 'objects' },
    { char: '🔒', name: 'locked', keywords: ['lock','secure','private'], cat: 'objects' },
    { char: '🔓', name: 'unlocked', keywords: ['unlock','open'], cat: 'objects' },
    { char: '✉️', name: 'envelope', keywords: ['mail','email','letter'], cat: 'objects' },
    { char: '📦', name: 'package', keywords: ['package','box','delivery'], cat: 'objects' },
    { char: '📝', name: 'memo', keywords: ['memo','note','write','pencil'], cat: 'objects' },
    { char: '📚', name: 'books', keywords: ['books','read','library'], cat: 'objects' },
    { char: '📖', name: 'open book', keywords: ['book','read','study'], cat: 'objects' },
    { char: '💰', name: 'money bag', keywords: ['money','rich','dollar','bag'], cat: 'objects' },
    { char: '💵', name: 'dollar banknote', keywords: ['money','cash','dollar'], cat: 'objects' },
    { char: '💳', name: 'credit card', keywords: ['credit card','payment','money'], cat: 'objects' },
    { char: '⏰', name: 'alarm clock', keywords: ['alarm','clock','time','wake'], cat: 'objects' },
    { char: '⏳', name: 'hourglass flowing', keywords: ['hourglass','time','sand'], cat: 'objects' },
    { char: '🧲', name: 'magnet', keywords: ['magnet','attract'], cat: 'objects' },
    { char: '🔧', name: 'wrench', keywords: ['wrench','tool','fix'], cat: 'objects' },
    { char: '🔨', name: 'hammer', keywords: ['hammer','tool','build'], cat: 'objects' },
    { char: '⚙️', name: 'gear', keywords: ['gear','settings','cog'], cat: 'objects' },
    { char: '🧪', name: 'test tube', keywords: ['test tube','science','lab'], cat: 'objects' },
    { char: '💊', name: 'pill', keywords: ['pill','medicine','drug'], cat: 'objects' },
    { char: '🩹', name: 'adhesive bandage', keywords: ['bandage','bandaid','heal'], cat: 'objects' },
    { char: '🎁', name: 'wrapped gift', keywords: ['gift','present','birthday'], cat: 'objects' },
    { char: '🎀', name: 'ribbon', keywords: ['ribbon','bow','gift'], cat: 'objects' },
    { char: '🎈', name: 'balloon', keywords: ['balloon','party','birthday'], cat: 'objects' },
    { char: '🎉', name: 'party popper', keywords: ['party','celebrate','congrats'], cat: 'objects' },
    { char: '🎊', name: 'confetti ball', keywords: ['confetti','celebrate','party'], cat: 'objects' },
    { char: '🎄', name: 'Christmas tree', keywords: ['christmas','tree','holiday'], cat: 'objects' },
    { char: '🎃', name: 'jack-o-lantern', keywords: ['halloween','pumpkin','scary'], cat: 'objects' },
    { char: '🪄', name: 'magic wand', keywords: ['magic','wand','sparkle'], cat: 'objects' },
    { char: '🧸', name: 'teddy bear', keywords: ['teddy','bear','toy','stuffed'], cat: 'objects' },

    // ── Symbols ──
    { char: '❤️', name: 'red heart', keywords: ['heart','love','red'], cat: 'symbols' },
    { char: '🧡', name: 'orange heart', keywords: ['heart','love','orange'], cat: 'symbols' },
    { char: '💛', name: 'yellow heart', keywords: ['heart','love','yellow'], cat: 'symbols' },
    { char: '💚', name: 'green heart', keywords: ['heart','love','green'], cat: 'symbols' },
    { char: '💙', name: 'blue heart', keywords: ['heart','love','blue'], cat: 'symbols' },
    { char: '💜', name: 'purple heart', keywords: ['heart','love','purple'], cat: 'symbols' },
    { char: '🖤', name: 'black heart', keywords: ['heart','love','black'], cat: 'symbols' },
    { char: '🤍', name: 'white heart', keywords: ['heart','love','white'], cat: 'symbols' },
    { char: '🤎', name: 'brown heart', keywords: ['heart','love','brown'], cat: 'symbols' },
    { char: '🩷', name: 'pink heart', keywords: ['heart','love','pink'], cat: 'symbols' },
    { char: '💔', name: 'broken heart', keywords: ['heart','broken','sad','love'], cat: 'symbols' },
    { char: '❣️', name: 'heart exclamation', keywords: ['heart','love','exclamation'], cat: 'symbols' },
    { char: '💕', name: 'two hearts', keywords: ['hearts','love'], cat: 'symbols' },
    { char: '💞', name: 'revolving hearts', keywords: ['hearts','love','spin'], cat: 'symbols' },
    { char: '💓', name: 'beating heart', keywords: ['heart','beat','love'], cat: 'symbols' },
    { char: '💗', name: 'growing heart', keywords: ['heart','growing','love'], cat: 'symbols' },
    { char: '💖', name: 'sparkling heart', keywords: ['heart','sparkle','love'], cat: 'symbols' },
    { char: '💘', name: 'heart with arrow', keywords: ['heart','arrow','love','cupid'], cat: 'symbols' },
    { char: '💝', name: 'heart with ribbon', keywords: ['heart','gift','love','valentine'], cat: 'symbols' },
    { char: '💟', name: 'heart decoration', keywords: ['heart','love','decoration'], cat: 'symbols' },
    { char: '💯', name: 'hundred points', keywords: ['100','perfect','score'], cat: 'symbols' },
    { char: '💢', name: 'anger symbol', keywords: ['anger','angry','mad'], cat: 'symbols' },
    { char: '💥', name: 'collision', keywords: ['boom','explosion','crash'], cat: 'symbols' },
    { char: '💫', name: 'dizzy', keywords: ['dizzy','star','sparkle'], cat: 'symbols' },
    { char: '💦', name: 'sweat droplets', keywords: ['sweat','water','drops'], cat: 'symbols' },
    { char: '💨', name: 'dashing away', keywords: ['wind','dash','fast'], cat: 'symbols' },
    { char: '🕳️', name: 'hole', keywords: ['hole','void'], cat: 'symbols' },
    { char: '💬', name: 'speech balloon', keywords: ['speech','chat','message','talk'], cat: 'symbols' },
    { char: '💭', name: 'thought balloon', keywords: ['thought','think','bubble'], cat: 'symbols' },
    { char: '💤', name: 'zzz', keywords: ['sleep','zzz','tired'], cat: 'symbols' },
    { char: '✅', name: 'check mark button', keywords: ['check','done','yes','green'], cat: 'symbols' },
    { char: '❌', name: 'cross mark', keywords: ['no','wrong','x','delete'], cat: 'symbols' },
    { char: '❓', name: 'question mark', keywords: ['question','?','what'], cat: 'symbols' },
    { char: '❗', name: 'exclamation mark', keywords: ['exclamation','!','alert'], cat: 'symbols' },
    { char: '‼️', name: 'double exclamation mark', keywords: ['exclamation','!!','alert'], cat: 'symbols' },
    { char: '⭕', name: 'hollow red circle', keywords: ['circle','red','o'], cat: 'symbols' },
    { char: '🚫', name: 'prohibited', keywords: ['no','forbidden','banned'], cat: 'symbols' },
    { char: '♻️', name: 'recycling symbol', keywords: ['recycle','green','environment'], cat: 'symbols' },
    { char: '✨', name: 'sparkles', keywords: ['sparkle','star','shine','magic'], cat: 'symbols' },
    { char: '🔴', name: 'red circle', keywords: ['red','circle','dot'], cat: 'symbols' },
    { char: '🟠', name: 'orange circle', keywords: ['orange','circle','dot'], cat: 'symbols' },
    { char: '🟡', name: 'yellow circle', keywords: ['yellow','circle','dot'], cat: 'symbols' },
    { char: '🟢', name: 'green circle', keywords: ['green','circle','dot'], cat: 'symbols' },
    { char: '🔵', name: 'blue circle', keywords: ['blue','circle','dot'], cat: 'symbols' },
    { char: '🟣', name: 'purple circle', keywords: ['purple','circle','dot'], cat: 'symbols' },
    { char: '⚪', name: 'white circle', keywords: ['white','circle','dot'], cat: 'symbols' },
    { char: '⚫', name: 'black circle', keywords: ['black','circle','dot'], cat: 'symbols' },

    // ── Flags ──
    { char: '🏁', name: 'chequered flag', keywords: ['flag','race','finish'], cat: 'flags' },
    { char: '🚩', name: 'triangular flag', keywords: ['flag','red flag','warning'], cat: 'flags' },
    { char: '🎌', name: 'crossed flags', keywords: ['flag','japan','celebrate'], cat: 'flags' },
    { char: '🏴', name: 'black flag', keywords: ['flag','black','pirate'], cat: 'flags' },
    { char: '🏳️', name: 'white flag', keywords: ['flag','white','surrender'], cat: 'flags' },
    { char: '🏳️‍🌈', name: 'rainbow flag', keywords: ['pride','lgbtq','rainbow','flag'], cat: 'flags' },
    { char: '🇺🇸', name: 'flag United States', keywords: ['usa','america','flag','us'], cat: 'flags' },
    { char: '🇬🇧', name: 'flag United Kingdom', keywords: ['uk','britain','flag','gb'], cat: 'flags' },
    { char: '🇨🇦', name: 'flag Canada', keywords: ['canada','flag'], cat: 'flags' },
    { char: '🇦🇺', name: 'flag Australia', keywords: ['australia','flag'], cat: 'flags' },
    { char: '🇩🇪', name: 'flag Germany', keywords: ['germany','flag'], cat: 'flags' },
    { char: '🇫🇷', name: 'flag France', keywords: ['france','flag','french'], cat: 'flags' },
    { char: '🇮🇹', name: 'flag Italy', keywords: ['italy','flag','italian'], cat: 'flags' },
    { char: '🇪🇸', name: 'flag Spain', keywords: ['spain','flag','spanish'], cat: 'flags' },
    { char: '🇯🇵', name: 'flag Japan', keywords: ['japan','flag','japanese'], cat: 'flags' },
    { char: '🇰🇷', name: 'flag South Korea', keywords: ['korea','flag','korean'], cat: 'flags' },
    { char: '🇨🇳', name: 'flag China', keywords: ['china','flag','chinese'], cat: 'flags' },
    { char: '🇮🇳', name: 'flag India', keywords: ['india','flag','indian'], cat: 'flags' },
    { char: '🇧🇷', name: 'flag Brazil', keywords: ['brazil','flag'], cat: 'flags' },
    { char: '🇲🇽', name: 'flag Mexico', keywords: ['mexico','flag','mexican'], cat: 'flags' },
    { char: '🇷🇺', name: 'flag Russia', keywords: ['russia','flag'], cat: 'flags' }
  ]
};
